import { createFileRoute } from '@tanstack/react-router';
import { useEffect,useState } from 'react';
import { ArrowRight,CheckCircle2,RefreshCw } from 'lucide-react';
import { AdminWorkspaceShell } from '@/components/admin/AdminWorkspaceShell';
import { supabase } from '@/lib/supabase';
export const Route=createFileRoute('/admin-approvals')({component:AdminApprovals});
type QueueKey='payments'|'intake'|'returning'|'accounts'|'missed';
type Queue={key:QueueKey;title:string;description:string;table:'fitness_payment_requests'|'fitness_new_member_requests'|'fitness_returning_member_claims'|'staff_profiles'|'staff_missed_scan_requests';fields:string;order:string;href:string;nextStep:string;roles:string[];legacy?:boolean};
type QueueState={count:number|null;examples:string[];error:string|null};
// New registrations and renewals never create approval requests. Keep existing pending legacy rows accessible so records aren't lost.
const queues:Queue[]=[
 {key:'accounts',title:'Staff account requests',description:'Staff accounts awaiting the existing authorisation process.',table:'staff_profiles',fields:'id,full_name,created_at',order:'created_at',href:'/staff-admin#staff',nextStep:'Open Staff Management to handle the request.',roles:['admin']},
 {key:'missed',title:'Staff missed-scan requests',description:'Existing staff attendance correction requests.',table:'staff_missed_scan_requests',fields:'id,work_date,kind,created_at',order:'created_at',href:'/staff-missed-scans',nextStep:'Open the staff attendance request page.',roles:['admin']},
 {key:'payments',title:'Older payment requests',description:'Only requests entered before the direct-payment change. New reception payments will be recorded directly as successful revenue.',table:'fitness_payment_requests',fields:'id,receipt_number,amount,submitted_at',order:'submitted_at',href:'/management-payment-desk#approvals',nextStep:'Resolve old pending entries in the original payment desk.',roles:['admin','owner','manager'],legacy:true},
 {key:'intake',title:'Older new-member requests',description:'Requests entered under the previous process. New reception registrations do not need approval.',table:'fitness_new_member_requests',fields:'id,receipt_number,full_name,submitted_at',order:'submitted_at',href:'/management-new-member-intake#review',nextStep:'Resolve any old records without creating duplicate member profiles.',roles:['admin','owner','manager'],legacy:true},
 {key:'returning',title:'Older returning-member claims',description:'Previous pending claims only. Renewals and REGOFF do not create approval requests.',table:'fitness_returning_member_claims',fields:'id,full_name,submitted_at',order:'submitted_at',href:'/management-payment-desk#approvals',nextStep:'Resolve historical claims only.',roles:['admin','owner'],legacy:true},
];
function describe(row:Record<string,unknown>,key:QueueKey){if(key==='payments')return `${String(row['receipt_number']||'Payment request')} · ${new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(row['amount']||0))}`;if(key==='intake')return `${String(row['receipt_number']||'Old intake')} · ${String(row['full_name']||'Member')}`;if(key==='returning'||key==='accounts')return String(row['full_name']||'Applicant');return `${String(row['work_date']||'Date unknown')} · ${String(row['kind']||'Missed scan').replaceAll('_',' ')}`;}
function AdminApprovals(){const [role,setRole]=useState(''),[items,setItems]=useState<Record<string,QueueState>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0),[showLegacy,setShowLegacy]=useState(false);
 useEffect(()=>{let cancelled=false;void(async()=>{setLoading(true);setItems({});setError('');setRole('');try{
  const{data:auth,error:authError}=await supabase.auth.getUser();if(authError||!auth.user)throw Error('Sign in through the admin portal first.');
  const{data:staff,error:staffError}=await supabase.from('staff_users').select('role,active').eq('auth_user_id',auth.user.id).maybeSingle();if(staffError)throw staffError;
  const next=String(staff?.role||'').toLowerCase();if(!staff?.active||!['admin','owner','manager'].includes(next))throw Error('Management access required.');if(cancelled)return;setRole(next);
  const results=await Promise.all(queues.filter(q=>q.roles.includes(next)).map(async q=>{try{const{data,error:queueError,count}=await supabase.from(q.table).select(q.fields,{count:'exact'}).eq('status','pending').order(q.order,{ascending:false}).limit(3);if(queueError)throw queueError;return[q.key,{count,examples:(data||[]).map(row=>describe(row as unknown as Record<string,unknown>,q.key)),error:null}] as const;}catch(cause){return[q.key,{count:null,examples:[],error:cause instanceof Error?cause.message:'Unavailable'}] as const;}}));if(!cancelled)setItems(Object.fromEntries(results));
 }catch(cause){if(!cancelled)setError(cause instanceof Error?cause.message:'Unable to load requests.');}finally{if(!cancelled)setLoading(false);}})();return()=>{cancelled=true;};},[revision]);
 const render=(queue:Queue)=>{const state=items[queue.key];return <section key={queue.key} className="rounded-[22px] border border-[#dce8d9] bg-white p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><h3 className="text-xl font-black">{queue.title}</h3><span className="rounded-xl bg-[#edf6e7] px-3 py-2 text-lg font-black">{state?.count===null||state?.count===undefined?'—':state.count}</span></div><p className="mt-3 text-sm leading-6 text-[#637469]">{queue.description}</p>{state?.error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-xs text-red-800">Unable to load: {state.error}</p>}{!state?.error&&!!state?.examples.length&&<div className="mt-4 rounded-xl bg-[#f4f6f1] p-4">{state.examples.map((example,i)=><p key={`${queue.key}-${i}`} className="border-b py-2 text-sm last:border-0">{example}</p>)}</div>}{!state?.error&&state?.count===0&&<p className="mt-4 inline-flex gap-2 text-sm"><CheckCircle2 size={16}/> No pending requests.</p>}<p className="mt-4 text-xs text-[#667769]">{queue.nextStep}</p><a href={queue.href} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#193b2a] px-5 py-3 text-sm font-bold text-white">Open request <ArrowRight size={16}/></a></section>;};
 const activeQueues=queues.filter(q=>q.roles.includes(role)&&!q.legacy),oldQueues=queues.filter(q=>q.roles.includes(role)&&q.legacy);
 return <AdminWorkspaceShell title="Staff requests" subtitle="Staff account and attendance requests. Registration and renewal need no admin approval." active="/admin-approvals">
  <section className="mt-7 rounded-2xl border border-[#dce8d9] bg-white p-5 sm:p-7"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-2xl font-black">Staff requests</h2><p className="mt-2 text-sm text-[#627468]">New member registrations and renewals are completed at reception or through online payment; successful payments appear in revenue.</p></div><button type="button" disabled={loading} onClick={()=>setRevision(n=>n+1)} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-bold disabled:opacity-50"><RefreshCw size={16}/> Refresh</button></div>{loading&&<p role="status" className="mt-4 text-sm">Loading requests…</p>}{error&&<p role="alert" className="mt-4 text-sm text-red-800">{error}</p>}</section>
  {!loading&&!error&&<><div className="mt-5 grid gap-4 lg:grid-cols-2">{activeQueues.map(render)}{!activeQueues.length&&<p className="rounded-xl bg-white p-5 text-sm">There are no staff-request queues assigned to this role.</p>}</div>
   <section className="mt-7 rounded-2xl border border-[#dce8d9] bg-white p-5"><button type="button" aria-expanded={showLegacy} onClick={()=>setShowLegacy(v=>!v)} className="flex w-full items-center justify-between gap-3 text-left text-sm font-bold"><span>Older pending reception requests (from previous system)</span><span>{showLegacy?'Hide':'Show'}</span></button><p className="mt-2 text-xs text-[#667769]">These existing records are preserved, but new transactions do not enter these queues.</p>{showLegacy&&<div className="mt-4 grid gap-4 lg:grid-cols-2">{oldQueues.map(render)}</div>}</section>
  </>}
 </AdminWorkspaceShell>;
}
