import { createFileRoute } from '@tanstack/react-router';
import { ArrowLeft, ArrowRight, CreditCard, UserPlus, UserRound } from 'lucide-react';
export const Route = createFileRoute('/management-standard-plan')({ component: RegistrationChoices });
function RegistrationChoices() {
 return <main className="min-h-screen bg-[#f4f6f1] px-4 py-10 text-[#16221c]"><div className="mx-auto max-w-2xl"><a href="/reception-workspace" className="inline-flex items-center gap-2 text-sm font-bold text-[#356942]"><ArrowLeft size={17}/> Reception dashboard</a>
  <section className="mt-7 rounded-3xl border border-[#dce8d7] bg-white p-6 shadow-sm sm:p-9"><p className="text-xs font-black uppercase tracking-widest text-[#608565]">Memberships</p><h1 className="mt-2 text-3xl font-black">Register or renew</h1><p className="mt-4 text-sm leading-7 text-[#657568]">No admin approval. Choose how the customer wants to pay. Every successful payment is recorded in normal revenue.</p>
   <a href="/reception-register" className="mt-6 flex items-center gap-3 rounded-2xl bg-[#193b27] p-5 text-white"><UserPlus size={23}/><span className="flex-1"><strong className="block">Pay at reception</strong><span className="mt-1 block text-sm text-[#cdddcf]">New or existing member: find their record, choose a plan and record payment.</span></span><ArrowRight size={19}/></a>
   <a href="/login" className="mt-3 flex items-center gap-3 rounded-2xl border border-[#d7e4d3] bg-[#f8fbf7] p-5"><UserRound size={23}/><span className="flex-1"><strong className="block">Existing member: pay online</strong><span className="mt-1 block text-sm text-[#657568]">Sign in with the email on their gym record. Email login can connect their existing gym profile.</span></span><ArrowRight size={19}/></a>
   <a href="/join" className="mt-3 flex items-center gap-3 rounded-2xl border border-[#d7e4d3] bg-[#f8fbf7] p-5"><CreditCard size={23}/><span className="flex-1"><strong className="block">Join online</strong><span className="mt-1 block text-sm text-[#657568]">Create a member profile and pay through Paystack. REGOFF waives only the registration fee when used.</span></span><ArrowRight size={19}/></a>
   <p className="mt-5 text-xs leading-6 text-[#657568]">Reception payments are completed immediately after confirmed cash, POS or bank transfer. Historical imports remain separate and excluded from normal revenue.</p>
  </section></div></main>;
}
