import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { ArrowRight, CheckCircle2, Loader2, Search, UserPlus, RefreshCw } from 'lucide-react';
import { supabase } from '@/lib/supabase';

export const Route = createFileRoute('/reception-register')({ component: ReceptionRegister });
type Plan = { id: string; name: string; price: number; duration_days: number };
type Member = { id: string; full_name: string; phone: string | null; email: string | null };
type Result = { success: boolean; member_id: string; membership_id: string; revenue_recorded: boolean; payment_status: string; amount: number; transaction_type: string };
const input = 'mt-1.5 w-full min-w-0 rounded-xl border border-[#cbdacb] bg-white px-4 py-3 text-base text-[#193327] outline-none focus:border-[#427a43] disabled:opacity-50';
const money = (value: number) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 }).format(value);
const feeFor = (name: string) => name === 'Personal Training Only' ? 0 : name === 'Family Plan' ? 20000 : ['Semi-Annual','Monthly VIP Gold'].includes(name) ? 3000 : 7000;
const lagosToday = () => { const parts = new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Lagos',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()); const part = (name: string) => parts.find(item => item.type===name)?.value || ''; return `${part('year')}-${part('month')}-${part('day')}`; };
// Safe default: preview must never write to production while its database/Edge changes are only staged in GitHub.
const instantEnabled = import.meta.env.VITE_RECEPTION_INSTANT_ENABLED === 'true';

function ReceptionRegister() {
 const [access,setAccess] = useState(false); const [loading,setLoading] = useState(true); const [busy,setBusy] = useState(false);
 const [plans,setPlans] = useState<Plan[]>([]); const [error,setError] = useState(''); const [done,setDone] = useState<Result|null>(null);
 const [mode,setMode] = useState<'new'|'renewal'>('new');
 const [fullName,setFullName] = useState(''); const [email,setEmail] = useState(''); const [phone,setPhone] = useState('');
 const [memberQuery,setMemberQuery] = useState(''); const [matches,setMatches] = useState<Member[]>([]); const [member,setMember] = useState<Member|null>(null); const [searching,setSearching] = useState(false);
 const [planId,setPlanId] = useState(''); const [customDays,setCustomDays] = useState('30'); const [customPrice,setCustomPrice] = useState('');
 const [coupon,setCoupon] = useState(''); const [method,setMethod] = useState('Cash'); const [reference,setReference] = useState(''); const [notes,setNotes] = useState(''); const [fundsConfirmed,setFundsConfirmed] = useState(false);
 const [retryKey,setRetryKey] = useState(() => crypto.randomUUID());
 const plan = plans.find(item=>item.id===planId); const custom = plan?.name === 'Custom Plan'; const planAmount = custom ? Number(customPrice||0) : Number(plan?.price||0);
 const days = custom ? Number(customDays||0) : Number(plan?.duration_days||0);
 const cleanCoupon = coupon.trim().toUpperCase(); const invalidCoupon = !!cleanCoupon && cleanCoupon !== 'REGOFF';
 const fee = !plan || mode==='renewal' || cleanCoupon==='REGOFF' ? 0 : feeFor(plan.name); const total=planAmount+fee;
 useEffect(()=>{let live=true;void(async()=>{try{
  const {data:auth,error:authError}=await supabase.auth.getUser();if(authError||!auth.user)throw Error('Sign in through the reception portal.');
  const {data:staff,error:staffError}=await supabase.from('staff_users').select('role,active').eq('auth_user_id',auth.user.id).maybeSingle();
  if(staffError||!staff?.active||!['reception','admin','owner','manager'].includes(String(staff.role||'').toLowerCase()))throw Error('An active reception account is required.');
  const {data,error:planError}=await supabase.from('membership_plans').select('id,name,price,duration_days').eq('active',true).order('name');if(planError)throw planError;
  if(live){setPlans((data||[]) as Plan[]);setAccess(true);}
 }catch(cause){if(live)setError(cause instanceof Error?cause.message:'Unable to load registration.');}finally{if(live)setLoading(false);}})();return()=>{live=false;};},[]);
 useEffect(()=>{const term=memberQuery.trim().replace(/[%_,()\\]/g,' ');if(mode!=='renewal'||member||term.length<2){setMatches([]);setSearching(false);return;}
  let cancelled=false;setSearching(true);const timer=setTimeout(()=>void(async()=>{const {data,error:searchError}=await supabase.from('members').select('id,full_name,phone,email').or(`full_name.ilike.%${term}%,phone.ilike.%${term}%,email.ilike.%${term}%`).order('full_name').limit(8);
   if(cancelled)return;setMatches(searchError?[]:(data||[]) as Member[]);setSearching(false);if(searchError)setError('Member lookup unavailable. Try the directory.');})(),240);
  return()=>{cancelled=true;clearTimeout(timer);};},[memberQuery,member,mode]);
 const valid = useMemo(()=>!!plan&&planAmount>0&&Number.isFinite(planAmount)&&Number.isInteger(days)&&days>0&&days<=3650&&!invalidCoupon&&(mode==='new'?fullName.trim().length>=3&&email.includes('@')&&phone.trim().length>=10:!!member)&&fundsConfirmed&&(method==='Cash'||reference.trim().length>=6),[plan,planAmount,days,invalidCoupon,mode,fullName,email,phone,member,fundsConfirmed,method,reference]);
 function switchMode(next:'new'|'renewal'){setMode(next);setError('');setDone(null);setRetryKey(crypto.randomUUID());setFundsConfirmed(false);}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy||!instantEnabled||!access||!valid)return;setError('');setDone(null);
  if(!window.confirm(`${mode==='new'?'Register':'Renew'} ${mode==='new'?fullName.trim():member?.full_name}?\nRecord received payment: ${money(total)}.\nMembership will activate and the payment will appear in revenue immediately.`))return;
  setBusy(true);
  try{const {data,error:submitError}=await supabase.functions.invoke('reception-instant-register',{body:{fullName:mode==='new'?fullName.trim():member?.full_name||'',email:mode==='new'?email.trim().toLowerCase():member?.email||'',phone:mode==='new'?phone.trim():member?.phone||'',memberId:mode==='renewal'?member?.id:null,planId:plan!.id,startDate:lagosToday(),durationDays:days,planAmount,method,reference:reference.trim(),notes:notes.trim(),couponCode:mode==='new'?cleanCoupon:'',fundsConfirmed,idempotencyKey:retryKey}});
   if(submitError)throw submitError;if(!data?.success)throw Error(data?.error||'Result uncertain. Check the member directory before retrying.');setDone(data as Result);setRetryKey(crypto.randomUUID());
  }catch(cause){setError(cause instanceof Error?cause.message:'Could not confirm the transaction. Check the member profile before retrying.');}finally{setBusy(false);}
 }
 return <main className="min-h-screen bg-[#f4f6f1] px-4 py-7 text-[#193327] sm:px-7 lg:px-10"><div className="mx-auto max-w-4xl space-y-6">
  <header><p className="text-xs font-black uppercase tracking-widest text-[#54815c]">Reception / Memberships</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Register or renew</h1><p className="mt-2 text-sm leading-6 text-[#607366]">Find out whether the customer is already a member, select their plan, and record payment. No management approval is needed.</p></header>
  <div className="grid grid-cols-2 gap-2 rounded-2xl border border-[#dce8d7] bg-white p-2"><button type="button" aria-pressed={mode==='new'} onClick={()=>switchMode('new')} className={`rounded-xl p-4 text-sm font-black ${mode==='new'?'bg-[#20432b] text-white':'text-[#526e55]'}`}>New member</button><button type="button" aria-pressed={mode==='renewal'} onClick={()=>switchMode('renewal')} className={`rounded-xl p-4 text-sm font-black ${mode==='renewal'?'bg-[#20432b] text-white':'text-[#526e55]'}`}>Existing member / renewal</button></div>
  {!instantEnabled&&<p role="status" className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><strong>Preview only:</strong> You can review this form but cannot submit real registrations or payments yet. The new server process has not been tested or enabled. Your live system has not changed.</p>}
  {loading&&<p role="status" className="rounded-xl bg-white p-5 text-sm"><Loader2 size={17} className="mr-2 inline animate-spin"/>Loading membership plans…</p>}
  {!!error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-900">{error}</p>}
  {done&&<section role="status" className="rounded-2xl border border-green-300 bg-green-50 p-5"><h2 className="flex items-center gap-2 text-lg font-black text-green-900"><CheckCircle2 size={21}/> {done.transaction_type==='new'?'Member registered':'Membership renewed'} successfully.</h2><p className="mt-2 text-sm text-green-900">Membership active. Payment of {money(Number(done.amount))} recorded as successful and included in standard revenue reporting.</p><a href={`/reception-member/${encodeURIComponent(done.member_id)}`} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#20432b] px-4 py-3 text-sm font-bold text-white">Open member profile <ArrowRight size={16}/></a></section>}
  {!loading&&access&&!done&&<form onSubmit={event=>void submit(event)} className="space-y-5">
   <section className="rounded-2xl border border-[#dce8d7] bg-white p-5 sm:p-7"><h2 className="text-xl font-black">1. {mode==='new'?'New member details':'Find the existing member'}</h2>
    {mode==='new'?<><p className="mt-2 text-sm text-[#607366]">Already attended the gym? Choose “Existing member / renewal” above to avoid duplicate records.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Full name<input className={input} autoComplete="name" required minLength={3} disabled={busy} value={fullName} onChange={e=>setFullName(e.target.value)}/></label><label className="text-sm font-bold">Phone number<input className={input} autoComplete="tel" type="tel" required minLength={10} disabled={busy} value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="text-sm font-bold sm:col-span-2">Email address<input className={input} autoComplete="email" type="email" required disabled={busy} value={email} onChange={e=>setEmail(e.target.value)}/></label></div></>:
    <><p className="mt-2 text-sm text-[#607366]">Search their name, phone or email and select the correct profile. Their old membership history will be preserved.</p>{member?<div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-[#edf6e9] p-4"><div><strong>{member.full_name}</strong><p className="mt-1 text-xs">{member.phone||member.email||'Member profile'}</p></div><button type="button" onClick={()=>{setMember(null);setMemberQuery('');setRetryKey(crypto.randomUUID());}} className="text-sm font-bold underline">Change member</button></div>:<><label className="mt-4 flex items-center gap-2 rounded-xl border bg-white px-3"><Search size={19}/><span className="sr-only">Search existing member</span><input className="w-full min-w-0 py-4 text-base outline-none" type="search" value={memberQuery} onChange={e=>setMemberQuery(e.target.value)} placeholder="Name, phone or email"/></label><div className="mt-2 space-y-2" aria-live="polite">{searching&&<p className="text-sm">Searching…</p>}{matches.map(person=><button type="button" key={person.id} onClick={()=>{setMember(person);setMatches([]);setError('');}} className="flex w-full items-center justify-between gap-3 rounded-xl border bg-[#fbfdfb] p-4 text-left text-sm hover:border-[#427a43]"><span><strong className="block">{person.full_name}</strong><span>{person.phone||person.email||'No contact'}</span></span><ArrowRight size={17}/></button>)}{!searching&&memberQuery.trim().length>=2&&!matches.length&&<p className="text-sm text-[#607366]">No match found? Check the full directory or register them as new using REGOFF if they previously attended.</p>}</div></>}<a href="/login" className="mt-4 inline-flex text-xs font-bold text-[#356942] underline">Already has an online profile? They can renew and pay on their dashboard.</a></>}
   </section>
   <section className="rounded-2xl border border-[#dce8d7] bg-white p-5 sm:p-7"><h2 className="text-xl font-black">2. Membership and price</h2><label className="mt-5 block text-sm font-bold">Membership plan<select className={input} required disabled={busy} value={planId} onChange={e=>setPlanId(e.target.value)}><option value="">Choose a plan</option>{plans.map(item=><option key={item.id} value={item.id}>{item.name} — {money(Number(item.price))}</option>)}</select></label>{custom&&<div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Custom price (₦)<input className={input} type="number" required min="1" max="100000000" step="0.01" disabled={busy} value={customPrice} onChange={e=>setCustomPrice(e.target.value)}/></label><label className="text-sm font-bold">Duration (days)<input className={input} type="number" required min="1" max="3650" step="1" disabled={busy} value={customDays} onChange={e=>setCustomDays(e.target.value)}/></label></div>}{mode==='new'?<label className="mt-4 block text-sm font-bold">Registration fee coupon (optional)<input className={input} autoComplete="off" disabled={busy} value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="Enter REGOFF"/>{invalidCoupon&&<span className="mt-2 block text-xs text-red-700">Invalid code. Use REGOFF or leave blank.</span>}{cleanCoupon==='REGOFF'&&<span className="mt-2 block text-xs font-bold text-green-700">REGOFF applied: registration fee removed.</span>}</label>:<p className="mt-4 rounded-xl bg-[#edf6e9] p-3 text-sm text-[#356942]">Renewals never pay a new registration fee.</p>}
    <div className="mt-5 space-y-2 rounded-xl bg-[#edf6e9] p-4 text-sm"><p className="flex justify-between gap-2"><span>Membership</span><strong>{money(planAmount)}</strong></p><p className="flex justify-between gap-2"><span>Registration fee</span><strong>{fee===0&&mode==='new'&&cleanCoupon==='REGOFF'?<><s>{money(plan?feeFor(plan.name):0)}</s> {money(0)}</>:money(fee)}</strong></p><p className="flex justify-between gap-2 border-t border-[#cadcc4] pt-3 text-lg font-black"><span>Total to collect</span><span>{money(total)}</span></p></div></section>
   <section className="rounded-2xl border border-[#dce8d7] bg-white p-5 sm:p-7"><h2 className="text-xl font-black">3. Record payment and finish</h2><p className="mt-2 text-sm text-[#607366]">Once you receive payment, complete this step. Membership activates immediately and the payment appears in revenue. No approval.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Payment method<select className={input} value={method} disabled={busy} onChange={e=>setMethod(e.target.value)}><option>Cash</option><option>POS</option><option>Bank Transfer</option></select></label><label className="text-sm font-bold">{method==='Cash'?'Receipt number (optional)':'POS / bank reference'}<input className={input} required={method!=='Cash'} minLength={method==='Cash'?undefined:6} disabled={busy} value={reference} onChange={e=>setReference(e.target.value)} placeholder={method==='Cash'?'Optional':'Real transaction reference'}/></label></div><label className="mt-4 block text-sm font-bold">Collection note (optional)<textarea className={input} rows={2} disabled={busy} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Any useful payment details"/></label><label className="mt-5 flex items-start gap-3 rounded-xl border border-[#cadcc4] bg-[#f3f8f0] p-4 text-sm leading-6"><input type="checkbox" checked={fundsConfirmed} disabled={busy} onChange={e=>setFundsConfirmed(e.target.checked)} className="mt-1 size-5 shrink-0"/><span>I confirm the gym has received {money(total)} by {method}. For transfers, I checked the gym's bank credit, not just a screenshot.</span></label></section>
   <button type="submit" disabled={!instantEnabled||busy||!access||!valid} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#20432b] px-6 py-4 text-base font-black text-white disabled:cursor-not-allowed disabled:opacity-40">{busy?<Loader2 size={18} className="animate-spin"/>:mode==='new'?<UserPlus size={18}/>:<RefreshCw size={18}/>} {instantEnabled?mode==='new'?'Register member and record payment':'Renew membership and record payment':'Preview only — submission disabled'}</button>
  </form>}
 </div></main>;
}
