import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState, type FormEvent } from 'react';
import { ArrowRight, CheckCircle2, Loader2, Search, ShieldCheck, UserPlus } from 'lucide-react';
import { supabase } from '@/lib/supabase';

export const Route = createFileRoute('/reception-register')({ component: ReceptionRegister });
type Plan = { id: string; name: string; price: number; duration_days: number };
type Registration = { success: boolean; registration_id: string; member_id: string; access_active: boolean; payment_status: string; confirmed_revenue: boolean; amount: number };
const input = 'mt-1.5 w-full min-w-0 rounded-xl border border-[#cbdacb] bg-white px-4 py-3 text-base text-[#193327] outline-none focus:border-[#427a43] disabled:opacity-50';
const money = (value: number) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 }).format(value);
const feeFor = (name: string) => name === 'Personal Training Only' ? 0 : name === 'Family Plan' ? 20000 : ['Semi-Annual','Monthly VIP Gold'].includes(name) ? 3000 : 7000;
const lagosToday = () => { const parts = new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Lagos',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()); const part = (name: string) => parts.find(item => item.type===name)?.value || ''; return `${part('year')}-${part('month')}-${part('day')}`; };
// A Vercel preview must not activate a money-moving feature against a production database.
// Turn on only AFTER deploying and testing the new server-side RPC/Edge function and QR dispute protection.
const instantEnabled = import.meta.env.VITE_RECEPTION_INSTANT_ENABLED === 'true';

function ReceptionRegister() {
 const [access,setAccess] = useState(false); const [loading,setLoading] = useState(true); const [busy,setBusy] = useState(false);
 const [plans,setPlans] = useState<Plan[]>([]); const [error,setError] = useState(''); const [done,setDone] = useState<Registration|null>(null);
 const [fullName,setFullName] = useState(''); const [email,setEmail] = useState(''); const [phone,setPhone] = useState(''); const [planId,setPlanId] = useState('');
 const [customDays,setCustomDays] = useState('30'); const [customPrice,setCustomPrice] = useState(''); const [method,setMethod] = useState('Cash'); const [reference,setReference] = useState(''); const [notes,setNotes] = useState(''); const [fundsConfirmed,setFundsConfirmed] = useState(false);
 const [retryKey,setRetryKey] = useState(() => crypto.randomUUID());
 const plan = plans.find(item => item.id===planId); const custom = plan?.name === 'Custom Plan'; const planAmount = custom ? Number(customPrice || 0) : Number(plan?.price || 0);
 const days = custom ? Number(customDays || 0) : Number(plan?.duration_days || 0); const fee = plan ? feeFor(plan.name) : 0; const total = planAmount + fee;
 useEffect(() => { let live=true; void (async()=>{try{
  const {data:auth,error:authError}=await supabase.auth.getUser(); if(authError||!auth.user) throw Error('Sign in to Reception first.');
  const {data:staff,error:staffError}=await supabase.from('staff_users').select('active,role').eq('auth_user_id',auth.user.id).maybeSingle();
  if(staffError||!staff?.active||!['reception','admin','owner','manager'].includes(String(staff.role).toLowerCase())) throw Error('An active reception account is required.');
  const {data,error:planError}=await supabase.from('membership_plans').select('id,name,price,duration_days').eq('active',true).order('name'); if(planError) throw planError;
  if(live){setPlans((data||[]) as Plan[]);setAccess(true);}
 }catch(cause){if(live)setError(cause instanceof Error?cause.message:'Unable to load registration.');}finally{if(live)setLoading(false);}})(); return()=>{live=false;};},[]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy||!instantEnabled||!access)return;setError('');setDone(null);
  if(!plan||!fullName.trim()||!email.includes('@')||!phone.trim()||!Number.isFinite(total)||planAmount<=0||!Number.isInteger(days)||days<1||days>3650||notes.trim().length<12||!fundsConfirmed||(method!=='Cash'&&reference.trim().length<6)){setError('Complete the member details and confirm the actual collection before registering.');return;}
  if(!window.confirm(`Register ${fullName.trim()} and activate their ${plan.name} membership now?\nTotal recorded: ${money(total)}.\nThis collection will NOT count as confirmed revenue until another manager reconciles it.`))return;
  setBusy(true);
  try{const {data,error:submitError}=await supabase.functions.invoke('reception-instant-register',{body:{fullName:fullName.trim(),email:email.trim().toLowerCase(),phone:phone.trim(),planId:plan.id,startDate:lagosToday(),durationDays:days,planAmount,method,reference:reference.trim(),notes:notes.trim(),fundsConfirmed,idempotencyKey:retryKey}});
   if(submitError)throw submitError;if(!data?.success)throw Error(data?.error||'Result uncertain. Check the member directory before retrying.');setDone(data as Registration);setRetryKey(crypto.randomUUID());
  }catch(cause){setError(cause instanceof Error?cause.message:'Registration result uncertain. Check the directory before retrying with the same form.');}finally{setBusy(false);}
 }
 return <main className="min-h-screen bg-[#f4f6f1] px-4 py-7 text-[#193327] sm:px-7 lg:px-10"><div className="mx-auto max-w-5xl space-y-6">
  <header><p className="text-xs font-black uppercase tracking-widest text-[#54815c]">Reception / New members</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Register a new member</h1><p className="mt-2 text-sm leading-6 text-[#607366]">For someone who has never joined Super Plus. Complete the form once to create their profile and activate access.</p></header>
  <a href="/management-members" className="flex items-center justify-between gap-3 rounded-2xl border border-[#bad1b3] bg-[#edf6e9] p-4 text-sm font-semibold text-[#24492b]"><span><Search size={17} className="mr-2 inline"/>Already attended before? Find their existing profile—don't register them again or charge another registration fee.</span><ArrowRight size={18} className="shrink-0"/></a>
  {!instantEnabled && <p role="status" className="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><strong>Preview only:</strong> This screen shows the new one-step process. Registration is disabled until the secure database change, staff endpoint and post-registration reconciliation have been reviewed and enabled. The live registration system has not changed.</p>}
  {loading && <p role="status" className="rounded-2xl bg-white p-5 text-sm"><Loader2 size={17} className="mr-2 inline animate-spin"/>Loading plans and checking staff access…</p>}
  {!!error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-900">{error}</p>}
  {done && <section role="status" className="rounded-2xl border border-green-300 bg-green-50 p-5"><h2 className="flex items-center gap-2 text-lg font-black text-green-900"><CheckCircle2 size={21}/> Member registered. Access active.</h2><p className="mt-2 text-sm text-green-900">The collection is recorded for independent reconciliation; it is not yet confirmed revenue.</p><a href={`/reception-member/${encodeURIComponent(done.member_id)}`} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#20432b] px-4 py-3 text-sm font-bold text-white">View member profile <ArrowRight size={16}/></a></section>}
  {!loading&&access&&!done&&<form onSubmit={event=>void submit(event)} className="space-y-5">
   <section className="rounded-2xl border border-[#dce8d7] bg-white p-5 sm:p-7"><h2 className="text-xl font-black">1. Member details</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Full name<input className={input} autoComplete="name" required minLength={3} disabled={busy} value={fullName} onChange={e=>setFullName(e.target.value)}/></label><label className="text-sm font-bold">Phone number<input className={input} autoComplete="tel" type="tel" required minLength={10} disabled={busy} value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="text-sm font-bold sm:col-span-2">Email address<input className={input} autoComplete="email" type="email" required disabled={busy} value={email} onChange={e=>setEmail(e.target.value)}/></label></div></section>
   <section className="rounded-2xl border border-[#dce8d7] bg-white p-5 sm:p-7"><h2 className="text-xl font-black">2. Membership plan</h2><label className="mt-5 block text-sm font-bold">Choose plan<select className={input} required disabled={busy} value={planId} onChange={e=>setPlanId(e.target.value)}><option value="">Select membership</option>{plans.map(item=><option key={item.id} value={item.id}>{item.name} — {money(Number(item.price))}</option>)}</select></label>{custom&&<div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Custom price (₦)<input className={input} type="number" required min="1" max="100000000" step="0.01" disabled={busy} value={customPrice} onChange={e=>setCustomPrice(e.target.value)}/></label><label className="text-sm font-bold">Duration (days)<input className={input} type="number" required min="1" max="3650" step="1" disabled={busy} value={customDays} onChange={e=>setCustomDays(e.target.value)}/></label></div>}<div className="mt-5 space-y-2 rounded-xl bg-[#edf6e9] p-4 text-sm"><p className="flex justify-between gap-2"><span>Membership</span><strong>{money(planAmount)}</strong></p><p className="flex justify-between gap-2"><span>New-member registration fee</span><strong>{money(fee)}</strong></p><p className="flex justify-between gap-2 border-t border-[#cadcc4] pt-3 text-lg font-black"><span>Total collected</span><span>{money(total)}</span></p></div></section>
   <section className="rounded-2xl border border-[#dce8d7] bg-white p-5 sm:p-7"><h2 className="text-xl font-black">3. Confirm collection</h2><p className="mt-1 text-sm text-[#607366]">Registration activates access immediately. Record what you personally received; management reconciles the transaction afterward.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Payment method<select className={input} value={method} disabled={busy} onChange={e=>setMethod(e.target.value)}><option>Cash</option><option>POS</option><option>Bank Transfer</option></select></label><label className="text-sm font-bold">{method==='Cash'?'Cash receipt / reference (optional)':'Verified transaction reference'}<input className={input} required={method!=='Cash'} minLength={method==='Cash'?undefined:6} disabled={busy} value={reference} onChange={e=>setReference(e.target.value)} placeholder={method==='Cash'?'Optional':'From the POS or gym bank record'}/></label></div><label className="mt-4 block text-sm font-bold">Collection note<textarea className={input} rows={2} required minLength={12} disabled={busy} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Who received the money and how did you check it?"/></label><label className="mt-5 flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><input type="checkbox" checked={fundsConfirmed} disabled={busy} onChange={e=>setFundsConfirmed(e.target.checked)} className="mt-1 size-5 shrink-0"/><span>I personally counted the cash or confirmed the transaction in the gym's POS/bank records. A customer's screenshot alone is not enough.</span></label><p className="mt-4 flex items-start gap-2 text-xs leading-5 text-[#607366]"><ShieldCheck size={17} className="shrink-0"/>The member receives access now. Payment remains pending, not confirmed revenue, until a different manager reconciles it. A disputed collection cancels this provisional membership.</p></section>
   <button type="submit" disabled={!instantEnabled||busy||!access||!fundsConfirmed||!plan||!fullName.trim()||!email.trim()||!phone.trim()||planAmount<=0} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#20432b] px-6 py-4 text-base font-black text-white disabled:cursor-not-allowed disabled:opacity-40">{busy?<Loader2 size={18} className="animate-spin"/>:<UserPlus size={18}/>} {instantEnabled?'Register & activate member':'Register & activate (available after approval)'}</button>
  </form>}
 </div></main>;
}
