import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowLeft, Check, ImagePlus, Loader2, Trash2, Upload, Video } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { supabase } from '@/lib/supabase';
import { makeGalleryThumbnail } from '@/lib/gallery-thumbnail';

type Item = { id: string; title: string; category: string; media_type: 'image' | 'video'; storage_path: string; thumbnail_path: string | null; is_published: boolean; sort_order: number; created_at: string };
const categories = ['Gym','Equipment','Training','Classes','Spa & Recovery','Events'];
const BUCKET = 'gallery-media';
const allowedImages = ['image/jpeg','image/png','image/webp'];
const allowedVideos = ['video/mp4','video/webm'];
export const Route = createFileRoute('/staff-gallery')({ component: GalleryManagement });
function GalleryManagement() {
  const [checking, setChecking] = useState(true);
  const [authorized, setAuthorized] = useState(false);
  const [items, setItems] = useState<Item[]>([]);
  const [title, setTitle] = useState('');
  const [category, setCategory] = useState('Gym');
  const [files, setFiles] = useState<File[]>([]);
  const [uploading, setUploading] = useState(false);
  const [optimizing, setOptimizing] = useState(false);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  useEffect(() => { void (async () => { const { data: { user } } = await supabase.auth.getUser(); if (!user) { setChecking(false); return; } const { data } = await supabase.from('staff_users').select('role').eq('auth_user_id',user.id).eq('active',true).maybeSingle(); const ok = !!data && ['owner','admin','manager'].includes(String(data.role).toLowerCase()); setAuthorized(ok); setChecking(false); if (ok) await refresh(); })(); }, []);
  async function refresh() { const { data, error: queryError } = await supabase.from('gallery_media').select('id,title,category,media_type,storage_path,thumbnail_path,is_published,sort_order,created_at').order('sort_order',{ascending:true}).order('created_at',{ascending:false}); if (queryError) setError(`Could not load gallery: ${queryError.message}`); else { setItems((data || []) as Item[]); setError(''); } }
  function url(item: Item) { return supabase.storage.from(BUCKET).getPublicUrl(item.storage_path).data.publicUrl; }
  async function saveThumbnail(source: Blob, sourcePath: string) {
    const thumbnail = await makeGalleryThumbnail(source);
    const path = `thumbnails/${sourcePath.split('/').pop()?.replace(/\.[^.]+$/, '') || crypto.randomUUID()}.${thumbnail.type === 'image/webp' ? 'webp' : 'jpg'}`;
    const { error: uploadError } = await supabase.storage.from(BUCKET).upload(path,thumbnail,{contentType:thumbnail.type,upsert:false,cacheControl:'31536000'});
    if (uploadError) throw uploadError;
    return path;
  }
  function selectFiles(event: React.ChangeEvent<HTMLInputElement>) { const next = Array.from(event.target.files || []); setError(''); const invalid = next.find(file => { const img = allowedImages.includes(file.type); const vid = allowedVideos.includes(file.type); return !(img || vid) || file.size > (img ? 10 : 50) * 1024 * 1024; }); if (invalid) { setError('Choose JPG/PNG/WebP photos under 10 MB or MP4/WebM videos under 50 MB.'); setFiles([]); return; } setFiles(next); }
  async function upload() { if (!files.length || uploading || optimizing) return; setUploading(true); setError(''); setNotice(''); let completed=0; for (const file of files) { const type = allowedVideos.includes(file.type) ? 'video' : 'image'; const extension = file.name.split('.').pop()?.toLowerCase() || (type === 'video' ? 'mp4' : 'jpg'); const path = `media/${crypto.randomUUID()}.${extension}`; const { error: uploadError } = await supabase.storage.from(BUCKET).upload(path,file,{contentType:file.type,upsert:false,cacheControl:'3600'}); if (uploadError) { setError(`Upload failed for ${file.name}: ${uploadError.message}`); break; } let thumbnailPath: string | null = null; if (type === 'image') { try { thumbnailPath = await saveThumbnail(file,path); } catch (thumbnailError) { console.error('Gallery thumbnail generation failed',thumbnailError); } } const { error: insertError } = await supabase.from('gallery_media').insert({title:(files.length===1 ? title.trim() : '') || file.name.replace(/\.[^.]+$/,'').replace(/[-_]/g,' '),category,media_type:type,storage_path:path,thumbnail_path:thumbnailPath,is_published:false,sort_order:0}); if (insertError) { await supabase.storage.from(BUCKET).remove([path,...(thumbnailPath?[thumbnailPath]:[])]); setError(`Could not save ${file.name}: ${insertError.message}`); break; } completed++; } setUploading(false); setFiles([]); const input=document.getElementById('gallery-upload') as HTMLInputElement|null; if(input)input.value=''; if(completed)setNotice(`${completed} item${completed===1?'':'s'} uploaded as unpublished drafts. Review them below before publishing.`); await refresh(); }
  async function optimizeExisting() { if(optimizing||uploading)return; const pending=items.filter(item=>item.media_type==='image'&&!item.thumbnail_path); if(!pending.length)return; setOptimizing(true);setError('');setNotice('');let done=0;let errors=0; for(const item of pending){setBusyId(item.id);try{ const response=await fetch(url(item),{mode:'cors'});if(!response.ok)throw new Error(`Photo download failed (${response.status})`);const thumbnailPath=await saveThumbnail(await response.blob(),item.storage_path);const {error: updateError}=await supabase.from('gallery_media').update({thumbnail_path:thumbnailPath}).eq('id',item.id);if(updateError){await supabase.storage.from(BUCKET).remove([thumbnailPath]);throw updateError;}done++;}catch(cause){console.error('Could not optimize gallery photo',item.title,cause);errors++;}setNotice(`Optimized ${done} of ${pending.length} photos${errors?` · ${errors} failed`:''}.`);}setBusyId(null);setOptimizing(false);await refresh();if(errors)setError(`${errors} photo(s) could not be optimized. Try again later; originals remain available.`);else setNotice(`Optimized all ${done} existing photos. Gallery cards will now use smaller images.`); }
  async function update(item: Item, field: 'is_published' | 'title' | 'category' | 'sort_order', value: string | boolean | number) { setBusyId(item.id); const { error: updateError } = await supabase.from('gallery_media').update({[field]:value}).eq('id',item.id); if(updateError)setError(updateError.message); else await refresh(); setBusyId(null); }
  async function remove(item:Item) { if(!window.confirm(`Delete ${item.title} permanently?`))return; setBusyId(item.id); const {error: deleteError}=await supabase.from('gallery_media').delete().eq('id',item.id); if(deleteError)setError(deleteError.message); else { const paths=[item.storage_path,...(item.thumbnail_path?[item.thumbnail_path]:[])];const {error: storageError}=await supabase.storage.from(BUCKET).remove(paths); if(storageError)setNotice('Gallery record deleted, but storage cleanup failed.'); await refresh(); } setBusyId(null); }
  if(checking)return <main className="section-shell py-20"><Loader2 className="animate-spin text-primary" aria-label="Checking access" /></main>;
  if(!authorized)return <main className="section-shell py-24"><h1 className="font-display text-4xl font-bold uppercase">Gallery Management</h1><p className="my-5 text-muted-foreground">Sign in with an authorised manager account to continue.</p><Button asChild><Link to="/staff">Staff sign in</Link></Button></main>;
  const unoptimized = items.filter(item=>item.media_type==='image'&&!item.thumbnail_path).length;
  return <main className="min-h-screen bg-muted/35 py-10 sm:py-16"><div className="section-shell max-w-6xl"><Link to="/portal" className="mb-7 inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-primary"><ArrowLeft className="size-4" /> Back to Staff Portal</Link><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-primary">Super Plus Fitness</p><h1 className="mt-2 font-display text-5xl font-black uppercase">Gallery Management</h1><p className="mt-3 text-sm text-muted-foreground">Upload photos and videos, arrange items and publish only what you approve.</p></div><Button asChild variant="outline"><Link to="/gallery">View public gallery</Link></Button></div>
    {error&&<p role="alert" className="mb-4 rounded-xl border border-red-300 bg-red-50 p-4 text-sm text-red-800">{error}</p>}{notice&&<p role="status" className="mb-4 rounded-xl border border-green-300 bg-green-50 p-4 text-sm text-green-800">{notice}</p>}
    {unoptimized>0&&<section className="mb-7 rounded-2xl border border-primary/30 bg-background p-5"><h2 className="font-display text-xl font-bold uppercase">Speed up gallery photos</h2><p className="my-3 text-sm text-muted-foreground">Create lightweight thumbnails for your {unoptimized} existing photo{unoptimized===1?'':'s'} without deleting or re-uploading the originals. Run this once; future photos are optimized automatically on upload.</p><Button onClick={()=>void optimizeExisting()} disabled={optimizing||uploading}>{optimizing?<Loader2 className="animate-spin"/>:<ImagePlus/>}{optimizing?' Optimizing photos…':` Optimize ${unoptimized} existing photo${unoptimized===1?'':'s'}`}</Button></section>}
    <section className="mb-10 rounded-3xl border bg-background p-5 shadow-sm sm:p-8"><div className="mb-6 flex items-center gap-3"><ImagePlus className="size-7 text-primary" /><h2 className="font-display text-3xl font-bold uppercase">Upload media</h2></div><div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Title for single upload<input className="h-11 rounded-lg border bg-background px-3" value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Strength training area" maxLength={140} /></label><label className="grid gap-2 text-sm font-semibold">Category<select className="h-11 rounded-lg border bg-background px-3" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(option=><option key={option}>{option}</option>)}</select></label></div><label className="mt-5 flex cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-primary/35 bg-primary/5 px-5 py-10 text-center hover:border-primary"><Upload className="mb-3 size-9 text-primary" /><span className="font-semibold">Choose photos and videos</span><span className="mt-2 text-xs text-muted-foreground">JPG, PNG, WebP up to 10 MB · MP4, WebM up to 50 MB each</span><input id="gallery-upload" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" multiple className="mt-4 block max-w-full text-xs" onChange={selectFiles} /></label>{files.length>0&&<p className="mt-4 text-sm text-muted-foreground">{files.length} file(s) selected: {files.map(file=>file.name).join(', ')}</p>}<Button className="mt-5" size="lg" onClick={()=>void upload()} disabled={!files.length||uploading||optimizing}>{uploading?<Loader2 className="animate-spin"/>:<Upload />} {uploading?'Uploading…':'Upload as drafts'}</Button></section>
    <section><h2 className="mb-5 font-display text-3xl font-black uppercase">Your media <span className="text-primary">({items.length})</span></h2>{!items.length?<div className="rounded-2xl border bg-background p-10 text-center text-muted-foreground">No uploaded media yet. Add your first gym photo or video above.</div>:<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(item=><article key={item.id} className="overflow-hidden rounded-2xl border bg-background shadow-sm"><div className="aspect-video bg-zinc-900">{item.media_type==='video'?<video className="h-full w-full object-cover" src={`${url(item)}#t=0.1`} controls preload="metadata" />:<img className="h-full w-full object-cover" src={item.thumbnail_path?supabase.storage.from(BUCKET).getPublicUrl(item.thumbnail_path).data.publicUrl:url(item)} alt={item.title} loading="lazy" />}</div><div className="grid gap-3 p-4"><span className={`w-fit rounded-full px-3 py-1 text-xs font-bold ${item.is_published?'bg-green-100 text-green-800':'bg-amber-100 text-amber-800'}`}>{item.is_published?'Published':'Draft'}</span><label className="grid gap-1 text-xs font-semibold">Title<input aria-label="Media title" key={`${item.id}-${item.title}`} defaultValue={item.title} maxLength={140} className="h-10 rounded-lg border px-2 text-sm" onBlur={e=>{if(e.target.value.trim()&&e.target.value.trim()!==item.title)void update(item,'title',e.target.value.trim());}} /></label><label className="grid gap-1 text-xs font-semibold">Category<select className="h-10 rounded-lg border px-2 text-sm" value={item.category} onChange={e=>void update(item,'category',e.target.value)}>{categories.map(option=><option key={option}>{option}</option>)}</select></label><label className="grid gap-1 text-xs font-semibold">Display order<input className="h-10 rounded-lg border px-2 text-sm" type="number" defaultValue={item.sort_order} key={`${item.id}-${item.sort_order}`} onBlur={e=>{if(Number(e.target.value)!==item.sort_order)void update(item,'sort_order',Number(e.target.value));}} /></label><div className="flex gap-2"><Button className="flex-1" size="sm" disabled={busyId===item.id||optimizing} onClick={()=>void update(item,'is_published',!item.is_published)}>{item.is_published?'Unpublish':<><Check className="size-4"/> Publish</>}</Button><Button size="sm" variant="destructive" aria-label={`Delete ${item.title}`} disabled={busyId===item.id||optimizing} onClick={()=>void remove(item)}><Trash2 className="size-4" /></Button></div></div></article>)}</div>}</section>
  </div></main>;
}
