import { Ionicons } from '@expo/vector-icons';
import { Link, Redirect } from 'expo-router';
import React, { useMemo } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card, Pill, Screen, usePalette } from '@/components/ui';
import { bossUnlocked, campaignPercent, campaignProgressText, completionKey, DIFFICULTIES, levelInfo, questReward, rankForLevel } from '@/lib/game';
import { useGame } from '@/store/game-store';
export default function TodayScreen(){const game=useGame(),c=usePalette(),s=useMemo(()=>styles(c),[c]);if(game.hydrated&&!game.onboarded)return <Redirect href="/onboarding"/>;const info=levelInfo(game.xp),rank=rankForLevel(info.level),chestCoins=20+Math.min(game.momentum,10)*3,plan=game.todayPlan,planItems=(plan?.questIds||[]).map(id=>game.quests.find(q=>q.id===id)).filter(Boolean) as typeof game.quests;const planDone=planItems.filter(q=>q.completedKeys.includes(completionKey(q.frequency))).length;const active=game.campaigns.filter(x=>x.status==='active');const suggested=game.quests.filter(q=>{const cp=game.campaigns.find(x=>x.id===q.campaignId);return cp&&cp.status==='active'&&!q.completedKeys.includes(completionKey(q.frequency))&&bossUnlocked(q,cp)}).slice(0,4);return <Screen><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
<View style={s.header}><View><Text style={s.kicker}>YOUR LIFE. YOUR RPG.</Text><Text style={s.title}>Level {info.level} {rank.name}</Text></View><Pressable onPress={game.toggleTheme} style={s.theme}><Text style={s.themeText}>{game.theme==='dark'?'☀️':'🌙'}</Text></Pressable></View>
<Card style={s.hero}><View style={s.row}><Pill>LEVEL {info.level}</Pill><Text style={s.xp}>{game.xp.toLocaleString()} XP</Text></View><Text style={s.heroTitle}>Build the person your goals require.</Text><View style={s.bar}><View style={[s.fill,{width:`${Math.max(4,info.progress*100)}%`}]} /></View><View style={[s.row,{marginTop:14}]}><Text style={s.meta}>🔥 {game.momentum} momentum</Text><Text style={s.meta}>🛡 {game.shields} shields</Text></View></Card>
<Card><View style={s.row}><View><Text style={s.section}>⚡ Smart Daily Plan</Text><Text style={s.meta}>{plan?`${planDone}/${planItems.length} planned quests complete`:'Let Quest decide what deserves focus today.'}</Text></View><Link href="/daily-plan" asChild><Pressable style={s.small}><Text style={s.smallText}>{plan?'OPEN':'PLAN'}</Text></Pressable></Link></View>{plan?<View style={s.bar}><View style={[s.fill,{width:`${planItems.length?planDone/planItems.length*100:0}%`}]} /></View>:null}</Card>
<View style={s.quickRow}><Link href="/evening-review" asChild><Pressable style={[s.quick,{backgroundColor:c.panel}]}><Text style={s.quickIcon}>🌙</Text><Text style={s.quickTitle}>Evening review</Text><Text style={s.meta}>{game.todayReview?`${game.todayReview.grade} · ${game.todayReview.score}%`:'Close today well'}</Text></Pressable></Link><Link href="/weekly-review" asChild><Pressable style={[s.quick,{backgroundColor:c.panel}]}><Text style={s.quickIcon}>📆</Text><Text style={s.quickTitle}>Weekly review</Text><Text style={s.meta}>See what moved</Text></Pressable></Link></View>
<Card><View style={s.row}><View><Text style={s.section}>🎁 Daily chest</Text><Text style={s.meta}>{game.dailyChestClaimed?'Claimed today':`+15 XP · +${chestCoins} coins`}</Text></View><Pressable disabled={game.dailyChestClaimed} onPress={game.claimDailyChest} style={[s.chest,game.dailyChestClaimed&&{backgroundColor:c.panel2}]}><Text style={[s.chestText,game.dailyChestClaimed&&{color:c.success}]}>{game.dailyChestClaimed?'CLAIMED':'OPEN'}</Text></Pressable></View></Card>
<Card><View style={s.row}><View><Text style={s.section}>⚔️ Weekly challenge</Text><Text style={s.meta}>Complete 5 quests this week</Text></View><Text style={s.week}>{Math.min(game.weeklyCount,5)}/5</Text></View><View style={s.bar}><View style={[s.fill,{width:`${Math.min(100,game.weeklyCount/5*100)}%`,backgroundColor:c.cyan}]} /></View>{game.weeklyCount>=5&&!game.weeklyChallengeClaimed?<Pressable onPress={game.claimWeeklyChallenge} style={s.claimWeek}><Text style={s.claimText}>Claim +150 XP · +80 coins</Text></Pressable>:null}</Card>
<View style={s.head}><Text style={s.section}>Recommended now</Text><Link href="/new-quest" asChild><Pressable><Text style={s.add}>+ Add</Text></Pressable></Link></View>{suggested.map(q=>{const campaign=game.campaigns.find(x=>x.id===q.campaignId),rw=questReward(q.difficulty,q.frequency);return <Pressable key={q.id} onPress={()=>game.completeQuest(q.id)}><Card style={s.quest}><View style={s.check}>{q.frequency==='once'?<Text>☠️</Text>:null}</View><View style={{flex:1}}><Text style={s.questTitle}>{q.title}</Text><Text style={s.meta}>{campaign?.emoji} {campaign?.title} · {DIFFICULTIES[q.difficulty].label}</Text></View><Text style={s.qxp}>+{rw.xp} XP</Text></Card></Pressable>})}
<View style={s.head}><Text style={s.section}>Your goals</Text><Link href="/new-campaign" asChild><Pressable><Text style={s.add}>+ Add goal</Text></Pressable></Link></View>{active.map(x=><Link key={x.id} href={{pathname:'/campaign/[id]',params:{id:x.id}}} asChild><Pressable><Card style={s.campaign}><Text style={s.campaignEmoji}>{x.emoji}</Text><View style={{flex:1}}><View style={s.row}><Text style={s.questTitle}>{x.title}</Text><Text style={s.percent}>{Math.round(campaignPercent(x))}%</Text></View><Text style={s.meta}>{x.subtitle}</Text><Text style={s.target}>{campaignProgressText(x)}</Text><View style={s.barSmall}><View style={[s.fill,{width:`${campaignPercent(x)}%`}]} /></View></View><Ionicons name="chevron-forward" size={18} color={c.muted}/></Card></Pressable></Link>)}</ScrollView></Screen>}
const styles=(c:any)=>StyleSheet.create({content:{padding:20,paddingTop:62,paddingBottom:120,gap:13},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{color:c.cyan,fontSize:11,fontWeight:'900',letterSpacing:1.4},title:{color:c.text,fontSize:28,fontWeight:'900',marginTop:5},theme:{width:45,height:45,borderRadius:15,borderWidth:1,borderColor:c.border,backgroundColor:c.panel,alignItems:'center',justifyContent:'center'},themeText:{fontSize:20},hero:{borderColor:c.primary},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},xp:{color:c.gold,fontWeight:'900'},heroTitle:{color:c.text,fontSize:23,fontWeight:'900',marginTop:18},bar:{height:9,borderRadius:99,backgroundColor:c.panel2,overflow:'hidden',marginTop:13},barSmall:{height:6,borderRadius:99,backgroundColor:c.panel2,overflow:'hidden',marginTop:10},fill:{height:'100%',backgroundColor:c.primary},meta:{color:c.muted,fontSize:12,lineHeight:18},section:{color:c.text,fontSize:17,fontWeight:'900'},small:{paddingHorizontal:13,paddingVertical:9,borderRadius:12,backgroundColor:c.primary},smallText:{color:'#fff',fontSize:10,fontWeight:'900'},quickRow:{flexDirection:'row',gap:10},quick:{flex:1,borderRadius:20,borderWidth:1,borderColor:c.border,padding:15},quickIcon:{fontSize:23},quickTitle:{color:c.text,fontWeight:'900',marginTop:9},chest:{backgroundColor:c.gold,borderRadius:13,paddingHorizontal:13,paddingVertical:10},chestText:{color:'#201608',fontSize:10,fontWeight:'900'},week:{color:c.cyan,fontWeight:'900'},claimWeek:{marginTop:12,backgroundColor:c.primary,borderRadius:13,padding:11,alignItems:'center'},claimText:{color:'#fff',fontWeight:'900',fontSize:12},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:10},add:{color:c.cyan,fontWeight:'900'},quest:{flexDirection:'row',alignItems:'center',gap:11},check:{width:34,height:34,borderRadius:11,borderWidth:2,borderColor:c.primary,alignItems:'center',justifyContent:'center'},questTitle:{color:c.text,fontWeight:'900',fontSize:15},qxp:{color:c.gold,fontWeight:'900',fontSize:12},campaign:{flexDirection:'row',alignItems:'center',gap:12},campaignEmoji:{fontSize:29},percent:{color:c.text,fontWeight:'900'},target:{color:c.cyan,fontSize:11,fontWeight:'900',marginTop:6}});