import DateTimePicker, { DateTimePickerAndroid } from '@react-native-community/datetimepicker';
import { Link, useLocalSearchParams } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Card, PrimaryButton, Screen, SecondaryButton, usePalette } from '@/components/ui';
import { bossUnlocked, campaignPace, campaignPercent, campaignProgressText, campaignVictoryReady, completionKey, DIFFICULTIES, questReward } from '@/lib/game';
import { useGame } from '@/store/game-store';

export default function CampaignScreen(){
  const {id}=useLocalSearchParams<{id:string}>(); const game=useGame(); const c=usePalette(); const s=useMemo(()=>styles(c),[c]);
  const campaign=game.campaigns.find(x=>x.id===id); const [current,setCurrent]=useState(campaign?String(campaign.progressCurrent):''); const [iosPicker,setIosPicker]=useState(false);
  if(!campaign)return <Screen><View style={s.center}><Text style={s.title}>Campaign not found.</Text></View></Screen>;
  const quests=game.quests.filter(q=>q.campaignId===campaign.id); const p=campaignPercent(campaign); const pace=campaignPace(campaign); const canWin=campaignVictoryReady(campaign,game.quests);
  const saveProgress=()=>{game.updateCampaignProgress(campaign.id,Number(current.replace(/,/g,'')));};
  const friendlyDate=(value?:string)=>{if(!value)return 'No deadline';const [y,m,d]=value.split('-').map(Number);return new Date(y,m-1,d).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});};
  const isoDate=(date:Date)=>{const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`;};
  const openDeadline=()=>{const value=campaign.deadline?new Date(`${campaign.deadline}T12:00:00`):new Date(Date.now()+30*86400000);const min=new Date();min.setHours(0,0,0,0);if(Platform.OS==='android'){DateTimePickerAndroid.open({value,mode:'date',minimumDate:min,onChange:(event,picked)=>{if(event.type==='set'&&picked)game.updateCampaign(campaign.id,{deadline:isoDate(picked)})}})}else setIosPicker(true);};
  return <Screen><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    <Text style={s.emoji}>{campaign.status==='completed'?'🏆':campaign.emoji}</Text><Text style={s.title}>{campaign.title}</Text><Text style={s.sub}>{campaign.subtitle}</Text>
    <Card><View style={s.row}><View><Text style={s.percent}>{Math.round(p)}%</Text><Text style={s.target}>{campaignProgressText(campaign)}</Text></View><View style={[s.pace,{borderColor:pace.status==='behind'||pace.status==='overdue'?c.danger:pace.status==='ahead'?c.success:c.cyan}]}><Text style={{color:pace.status==='behind'||pace.status==='overdue'?c.danger:pace.status==='ahead'?c.success:c.cyan,fontWeight:'900',fontSize:11}}>{pace.label}</Text></View></View><View style={s.bar}><View style={[s.fill,{width:`${p}%`}]} /></View><View style={s.milestones}>{[25,50,75,100].map(m=><View key={m} style={[s.mile,p>=m&&s.mileOn]}><Text style={s.mileText}>{p>=m?'✓ ':''}{m}%</Text></View>)}</View></Card>
    <Card><Text style={s.section}>Update progress</Text><View style={s.inline}><TextInput value={current} onChangeText={setCurrent} keyboardType="decimal-pad" style={s.input}/><Pressable onPress={saveProgress} style={s.smallBtn}><Text style={s.smallText}>Save</Text></Pressable></View><Text style={s.label}>TARGET DATE</Text><Pressable onPress={openDeadline} style={s.dateBtn}><Text style={s.dateIcon}>📅</Text><View style={{flex:1}}><Text style={s.dateValue}>{friendlyDate(campaign.deadline)}</Text><Text style={s.dateSub}>{campaign.deadline?'Tap to change':'Optional'}</Text></View><Text style={s.change}>Choose</Text></Pressable>{campaign.deadline?<Pressable onPress={()=>game.updateCampaign(campaign.id,{deadline:undefined})}><Text style={s.clear}>Remove deadline</Text></Pressable>:null}{Platform.OS==='ios'&&iosPicker?<View style={s.iosPicker}><DateTimePicker value={campaign.deadline?new Date(`${campaign.deadline}T12:00:00`):new Date(Date.now()+30*86400000)} mode="date" display="inline" minimumDate={new Date()} onChange={(_,picked)=>{if(picked)game.updateCampaign(campaign.id,{deadline:isoDate(picked)})}}/><Pressable onPress={()=>setIosPicker(false)}><Text style={s.done}>Done</Text></Pressable></View>:null}<Text style={s.coach}>🧭 {pace.status==='behind'||pace.status==='overdue'?'You are behind pace. Quest will prioritise this campaign in your daily plan.':pace.status==='ahead'?'You are ahead of pace. Keep the rhythm or give yourself breathing room.':pace.status==='none'?'Add a deadline to unlock pace coaching.':'You are moving at roughly the pace needed to hit the deadline.'}</Text></Card>
    <View style={s.head}><Text style={s.section}>Quest line</Text><Link href={{pathname:'/new-quest',params:{campaignId:campaign.id}}} asChild><Pressable><Text style={s.add}>+ Add</Text></Pressable></Link></View>
    <SecondaryButton title="✨ Add smart suggested quests" onPress={()=>game.addSmartSuggestedQuests(campaign.id)}/>
    {quests.map(q=>{const done=q.completedKeys.includes(completionKey(q.frequency)),unlock=bossUnlocked(q,campaign),rw=questReward(q.difficulty,q.frequency);return <Pressable key={q.id} disabled={done||!unlock||campaign.status==='completed'} onPress={()=>game.completeQuest(q.id)}><Card style={[s.quest,!unlock&&{opacity:.48},done&&{opacity:.55},q.frequency==='once'&&{borderColor:c.danger}]}><View style={{flex:1}}><Text style={s.questTitle}>{done?'✓ ':q.frequency==='once'?(unlock?'☠️ ':'🔒 '):''}{q.title}</Text><Text style={s.meta}>{q.frequency==='once'?'boss':q.frequency} · {DIFFICULTIES[q.difficulty].icon} {DIFFICULTIES[q.difficulty].label}{q.frequency==='once'?` · unlock ${q.unlockPercent}%`:''}</Text></View><Text style={s.xp}>+{rw.xp} XP</Text></Card></Pressable>})}
    {campaign.status==='completed'?<Card style={{borderColor:c.success}}><Text style={[s.section,{color:c.success}]}>🏆 Campaign complete</Text></Card>:canWin?<PrimaryButton title="🏆 Claim campaign victory · +500 XP" onPress={()=>game.claimCampaignVictory(campaign.id)}/>:<Card><Text style={s.meta}>{p<100?'Reach 100% progress. ':''}{quests.filter(q=>q.frequency==='once'&&!q.completedKeys.includes('done')).length} boss checkpoint(s) still undefeated.</Text></Card>}
  </ScrollView></Screen>;
}
const styles=(c:any)=>StyleSheet.create({content:{padding:20,paddingBottom:90,gap:12},center:{flex:1,alignItems:'center',justifyContent:'center'},emoji:{fontSize:54},title:{color:c.text,fontSize:32,fontWeight:'900'},sub:{color:c.muted,fontSize:16,lineHeight:22},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},percent:{color:c.text,fontSize:28,fontWeight:'900'},target:{color:c.cyan,fontWeight:'900',marginTop:4},pace:{borderWidth:1,borderRadius:999,paddingHorizontal:10,paddingVertical:7},bar:{height:9,borderRadius:99,backgroundColor:c.panel2,overflow:'hidden',marginTop:16},fill:{height:'100%',backgroundColor:c.primary},milestones:{flexDirection:'row',gap:6,marginTop:11},mile:{flex:1,borderRadius:11,paddingVertical:8,backgroundColor:c.panel2,alignItems:'center'},mileOn:{borderWidth:1,borderColor:c.success},mileText:{color:c.muted,fontSize:10,fontWeight:'900'},section:{color:c.text,fontSize:18,fontWeight:'900'},inline:{flexDirection:'row',gap:8,alignItems:'center',marginTop:10},input:{flex:1,minHeight:48,borderRadius:14,borderWidth:1,borderColor:c.border,backgroundColor:c.bg2,color:c.text,paddingHorizontal:13},smallBtn:{minHeight:48,paddingHorizontal:16,borderRadius:14,backgroundColor:c.primary,alignItems:'center',justifyContent:'center'},smallText:{color:'#fff',fontWeight:'900'},label:{color:c.muted,fontSize:10,fontWeight:'900',marginTop:14},dateBtn:{minHeight:58,borderRadius:15,borderWidth:1,borderColor:c.border,backgroundColor:c.bg2,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:13,marginTop:9},dateIcon:{fontSize:22},dateValue:{color:c.text,fontWeight:'900',fontSize:14},dateSub:{color:c.muted,fontSize:10,marginTop:2},change:{color:c.cyan,fontWeight:'900',fontSize:11},clear:{color:c.danger,fontWeight:'800',fontSize:11,textAlign:'right',marginTop:8},iosPicker:{marginTop:10,borderRadius:14,overflow:'hidden',backgroundColor:c.panel},done:{color:c.cyan,fontWeight:'900',textAlign:'right',padding:12},coach:{color:c.muted,lineHeight:19,marginTop:14},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:10},add:{color:c.cyan,fontWeight:'900'},quest:{flexDirection:'row',alignItems:'center',gap:10},questTitle:{color:c.text,fontWeight:'900',fontSize:15},meta:{color:c.muted,fontSize:12,lineHeight:18,marginTop:4},xp:{color:c.gold,fontWeight:'900',fontSize:12}});