import { router } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Screen, usePalette } from '@/components/ui';
import { useGame } from '@/store/game-store';

export default function OnboardingScreen(){
  const game=useGame(),c=usePalette(),s=useMemo(()=>styles(c),[c]);const[name,setName]=useState(game.name==='Adventurer'?'':game.name);
  const continueToGoal=()=>{game.setName(name);router.push('/new-campaign')};
  return <Screen><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    <View style={s.logo}><Text style={s.logoText}>⚡️</Text></View><Text style={s.kicker}>WELCOME TO QUEST</Text><Text style={s.title}>Your life is the RPG.</Text><Text style={s.lead}>Turn ambitions into campaigns, milestones into boss battles and real progress into XP.</Text>
    <View style={s.block}><Text style={s.label}>WHAT SHOULD QUEST CALL YOU?</Text><TextInput value={name} onChangeText={setName} placeholder="Your name" placeholderTextColor={c.muted} style={s.input} autoCapitalize="words" /></View>
    <View style={s.block}><Text style={s.label}>CHOOSE YOUR LOOK</Text><View style={s.themeRow}><Pressable onPress={()=>game.setTheme('dark')} style={[s.theme,game.theme==='dark'&&s.themeActive]}><Text style={s.themeIcon}>🌙</Text><Text style={s.themeText}>Dark</Text><Text style={s.themeSub}>Deep gradients</Text></Pressable><Pressable onPress={()=>game.setTheme('light')} style={[s.theme,game.theme==='light'&&s.themeActive]}><Text style={s.themeIcon}>☀️</Text><Text style={s.themeText}>Light</Text><Text style={s.themeSub}>Clean gradients</Text></Pressable></View></View>
    <View style={s.features}><Text style={s.item}>🚩 Choose several goals at once</Text><Text style={s.item}>⚔️ Quest builds your daily plan</Text><Text style={s.item}>☠️ Milestones unlock boss battles</Text><Text style={s.item}>🌙 Daily + weekly reviews keep you focused</Text><Text style={s.item}>🎁 Progress earns XP, coins and rewards</Text></View>
    <Pressable style={s.primary} onPress={continueToGoal}><Text style={s.primaryText}>Set up my goals</Text></Pressable><Pressable style={s.demo} onPress={()=>{game.setName(name);game.loadDemo();router.replace('/(tabs)')}}><Text style={s.demoText}>Explore with demo data</Text></Pressable>
    <Text style={s.privacy}>This beta starts local-first. Your goals and progress stay on this device during this testing phase.</Text>
  </ScrollView></Screen>
}
const styles=(c:any)=>StyleSheet.create({content:{padding:24,paddingTop:72,paddingBottom:50},logo:{width:62,height:62,borderRadius:21,backgroundColor:c.primary,alignItems:'center',justifyContent:'center'},logoText:{fontSize:30},kicker:{color:c.cyan,fontSize:11,fontWeight:'900',letterSpacing:1.4,marginTop:23},title:{color:c.text,fontSize:38,lineHeight:41,fontWeight:'900',marginTop:7},lead:{color:c.muted,fontSize:16,lineHeight:23,marginTop:14},block:{marginTop:25},label:{color:c.muted,fontWeight:'900',fontSize:10,letterSpacing:1},input:{minHeight:52,borderRadius:16,borderWidth:1,borderColor:c.border,backgroundColor:c.panel,color:c.text,paddingHorizontal:15,marginTop:8,fontWeight:'800'},themeRow:{flexDirection:'row',gap:10,marginTop:9},theme:{flex:1,minHeight:100,borderRadius:18,borderWidth:1,borderColor:c.border,backgroundColor:c.panel,alignItems:'center',justifyContent:'center'},themeActive:{borderColor:c.primary,borderWidth:2},themeIcon:{fontSize:27},themeText:{color:c.text,fontWeight:'900',marginTop:5},themeSub:{color:c.muted,fontSize:10,marginTop:2},features:{gap:10,marginTop:26},item:{color:c.text,fontWeight:'800',fontSize:14},primary:{minHeight:56,borderRadius:18,backgroundColor:c.primary,alignItems:'center',justifyContent:'center',marginTop:28},primaryText:{color:'#fff',fontWeight:'900',fontSize:16},demo:{minHeight:54,borderRadius:18,backgroundColor:c.panel,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center',marginTop:10},demoText:{color:c.text,fontWeight:'900'},privacy:{color:c.muted,textAlign:'center',fontSize:11,lineHeight:16,marginTop:18}});