/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin-announcements'
import { Route as AdminApprovalsRouteImport } from './routes/admin-approvals'
import { Route as AdminEngagementRouteImport } from './routes/admin-engagement'
import { Route as AdminHistoricalMembersRouteImport } from './routes/admin-historical-members'
import { Route as AdminMembersRouteImport } from './routes/admin-members'
import { Route as AdminWorkspaceRouteImport } from './routes/admin-workspace'
import { Route as AppRouteImport } from './routes/app'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as FamilyJoinRouteImport } from './routes/family-join'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HmoRouteImport } from './routes/hmo'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagementAttendanceRouteImport } from './routes/management-attendance'
import { Route as ManagementAttendanceExportRouteImport } from './routes/management-attendance-export'
import { Route as ManagementBookingsRouteImport } from './routes/management-bookings'
import { Route as ManagementCommunicationsRouteImport } from './routes/management-communications'
import { Route as ManagementCustomPlanRouteImport } from './routes/management-custom-plan'
import { Route as ManagementExpensesRouteImport } from './routes/management-expenses'
import { Route as ManagementFamilyRouteImport } from './routes/management-family'
import { Route as ManagementMemberCardRouteImport } from './routes/management-member-card'
import { Route as ManagementMemberCardsRouteImport } from './routes/management-member-cards'
import { Route as ManagementMemberFeedbackRouteImport } from './routes/management-member-feedback'
import { Route as ManagementMembersRouteImport } from './routes/management-members'
import { Route as ManagementNewMemberIntakeRouteImport } from './routes/management-new-member-intake'
import { Route as ManagementOperationsRouteImport } from './routes/management-operations'
import { Route as ManagementPaymentDeskRouteImport } from './routes/management-payment-desk'
import { Route as ManagementPayrollRouteImport } from './routes/management-payroll'
import { Route as ManagementPayrollExportRouteImport } from './routes/management-payroll-export'
import { Route as ManagementPersonalTrainingRouteImport } from './routes/management-personal-training'
import { Route as ManagementPreviewRouteImport } from './routes/management-preview'
import { Route as ManagementProfilesRouteImport } from './routes/management-profiles'
import { Route as ManagementRevenueRouteImport } from './routes/management-revenue'
import { Route as ManagementSalaryPaymentsRouteImport } from './routes/management-salary-payments'
import { Route as ManagementStaffRouteImport } from './routes/management-staff'
import { Route as ManagementStaffManagementRouteImport } from './routes/management-staff-management'
import { Route as ManagementStaffMonthlyRouteImport } from './routes/management-staff-monthly'
import { Route as ManagementStaffReviewRouteImport } from './routes/management-staff-review'
import { Route as ManagementStaffSupportRouteImport } from './routes/management-staff-support'
import { Route as ManagementStandardPlanRouteImport } from './routes/management-standard-plan'
import { Route as MemberRouteImport } from './routes/member'
import { Route as MemberFamilyRouteImport } from './routes/member-family'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MyQrRouteImport } from './routes/my-qr'
import { Route as PersonalTrainingRouteImport } from './routes/personal-training'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ReceptionCheckinRouteImport } from './routes/reception-checkin'
import { Route as ReceptionDashboardRouteImport } from './routes/reception-dashboard'
import { Route as ReceptionRegisterRouteImport } from './routes/reception-register'
import { Route as ReceptionWorkspaceRouteImport } from './routes/reception-workspace'
import { Route as SpaRecoveryRouteImport } from './routes/spa-recovery'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StaffAccountRequestsRouteImport } from './routes/staff-account-requests'
import { Route as StaffAdminRouteImport } from './routes/staff-admin'
import { Route as StaffAttendanceRouteImport } from './routes/staff-attendance'
import { Route as StaffAttendanceQrRouteImport } from './routes/staff-attendance-qr'
import { Route as StaffBlogRouteImport } from './routes/staff-blog'
import { Route as StaffGalleryRouteImport } from './routes/staff-gallery'
import { Route as StaffMissedScansRouteImport } from './routes/staff-missed-scans'
import { Route as StaffResetPasswordRouteImport } from './routes/staff-reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogArticleRouteImport } from './routes/blog.article'
import { Route as ManagementMemberPreviewMemberIdRouteImport } from './routes/management-member-preview.$memberId'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as PaymentMobileReturnRouteImport } from './routes/payment.mobile-return'
import { Route as PaymentPublicCallbackRouteImport } from './routes/payment.public-callback'
import { Route as PortalAdminRouteImport } from './routes/portal.admin'
import { Route as PortalReceptionRouteImport } from './routes/portal.reception'
import { Route as PortalStaffRouteImport } from './routes/portal.staff'
import { Route as ReceptionMemberMemberIdRouteImport } from './routes/reception-member.$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin-announcements',
  path: '/admin-announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin-approvals',
  path: '/admin-approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEngagementRoute = AdminEngagementRouteImport.update({
  id: '/admin-engagement',
  path: '/admin-engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHistoricalMembersRoute = AdminHistoricalMembersRouteImport.update({
  id: '/admin-historical-members',
  path: '/admin-historical-members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin-members',
  path: '/admin-members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkspaceRoute = AdminWorkspaceRouteImport.update({
  id: '/admin-workspace',
  path: '/admin-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyJoinRoute = FamilyJoinRouteImport.update({
  id: '/family-join',
  path: '/family-join',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HmoRoute = HmoRouteImport.update({
  id: '/hmo',
  path: '/hmo',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementAttendanceRoute = ManagementAttendanceRouteImport.update({
  id: '/management-attendance',
  path: '/management-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementAttendanceExportRoute =
  ManagementAttendanceExportRouteImport.update({
    id: '/management-attendance-export',
    path: '/management-attendance-export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManagementBookingsRoute = ManagementBookingsRouteImport.update({
  id: '/management-bookings',
  path: '/management-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementCommunicationsRoute =
  ManagementCommunicationsRouteImport.update({
    id: '/management-communications',
    path: '/management-communications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManagementCustomPlanRoute = ManagementCustomPlanRouteImport.update({
  id: '/management-custom-plan',
  path: '/management-custom-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementExpensesRoute = ManagementExpensesRouteImport.update({
  id: '/management-expenses',
  path: '/management-expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementFamilyRoute = ManagementFamilyRouteImport.update({
  id: '/management-family',
  path: '/management-family',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementMemberCardRoute = ManagementMemberCardRouteImport.update({
  id: '/management-member-card',
  path: '/management-member-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementMemberCardsRoute = ManagementMemberCardsRouteImport.update({
  id: '/management-member-cards',
  path: '/management-member-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementMemberFeedbackRoute =
  ManagementMemberFeedbackRouteImport.update({
    id: '/management-member-feedback',
    path: '/management-member-feedback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManagementMembersRoute = ManagementMembersRouteImport.update({
  id: '/management-members',
  path: '/management-members',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementNewMemberIntakeRoute =
  ManagementNewMemberIntakeRouteImport.update({
    id: '/management-new-member-intake',
    path: '/management-new-member-intake',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManagementOperationsRoute = ManagementOperationsRouteImport.update({
  id: '/management-operations',
  path: '/management-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementPaymentDeskRoute = ManagementPaymentDeskRouteImport.update({
  id: '/management-payment-desk',
  path: '/management-payment-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementPayrollRoute = ManagementPayrollRouteImport.update({
  id: '/management-payroll',
  path: '/management-payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementPayrollExportRoute = ManagementPayrollExportRouteImport.update({
  id: '/management-payroll-export',
  path: '/management-payroll-export',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementPersonalTrainingRoute =
  ManagementPersonalTrainingRouteImport.update({
    id: '/management-personal-training',
    path: '/management-personal-training',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManagementPreviewRoute = ManagementPreviewRouteImport.update({
  id: '/management-preview',
  path: '/management-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementProfilesRoute = ManagementProfilesRouteImport.update({
  id: '/management-profiles',
  path: '/management-profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRevenueRoute = ManagementRevenueRouteImport.update({
  id: '/management-revenue',
  path: '/management-revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementSalaryPaymentsRoute =
  ManagementSalaryPaymentsRouteImport.update({
    id: '/management-salary-payments',
    path: '/management-salary-payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManagementStaffRoute = ManagementStaffRouteImport.update({
  id: '/management-staff',
  path: '/management-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementStaffManagementRoute =
  ManagementStaffManagementRouteImport.update({
    id: '/management-staff-management',
    path: '/management-staff-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManagementStaffMonthlyRoute = ManagementStaffMonthlyRouteImport.update({
  id: '/management-staff-monthly',
  path: '/management-staff-monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementStaffReviewRoute = ManagementStaffReviewRouteImport.update({
  id: '/management-staff-review',
  path: '/management-staff-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementStaffSupportRoute = ManagementStaffSupportRouteImport.update({
  id: '/management-staff-support',
  path: '/management-staff-support',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementStandardPlanRoute = ManagementStandardPlanRouteImport.update({
  id: '/management-standard-plan',
  path: '/management-standard-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberFamilyRoute = MemberFamilyRouteImport.update({
  id: '/member-family',
  path: '/member-family',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQrRoute = MyQrRouteImport.update({
  id: '/my-qr',
  path: '/my-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalTrainingRoute = PersonalTrainingRouteImport.update({
  id: '/personal-training',
  path: '/personal-training',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionCheckinRoute = ReceptionCheckinRouteImport.update({
  id: '/reception-checkin',
  path: '/reception-checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionDashboardRoute = ReceptionDashboardRouteImport.update({
  id: '/reception-dashboard',
  path: '/reception-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionRegisterRoute = ReceptionRegisterRouteImport.update({
  id: '/reception-register',
  path: '/reception-register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionWorkspaceRoute = ReceptionWorkspaceRouteImport.update({
  id: '/reception-workspace',
  path: '/reception-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaRecoveryRoute = SpaRecoveryRouteImport.update({
  id: '/spa-recovery',
  path: '/spa-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAccountRequestsRoute = StaffAccountRequestsRouteImport.update({
  id: '/staff-account-requests',
  path: '/staff-account-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAdminRoute = StaffAdminRouteImport.update({
  id: '/staff-admin',
  path: '/staff-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAttendanceRoute = StaffAttendanceRouteImport.update({
  id: '/staff-attendance',
  path: '/staff-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAttendanceQrRoute = StaffAttendanceQrRouteImport.update({
  id: '/staff-attendance-qr',
  path: '/staff-attendance-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffBlogRoute = StaffBlogRouteImport.update({
  id: '/staff-blog',
  path: '/staff-blog',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffGalleryRoute = StaffGalleryRouteImport.update({
  id: '/staff-gallery',
  path: '/staff-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffMissedScansRoute = StaffMissedScansRouteImport.update({
  id: '/staff-missed-scans',
  path: '/staff-missed-scans',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffResetPasswordRoute = StaffResetPasswordRouteImport.update({
  id: '/staff-reset-password',
  path: '/staff-reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogArticleRoute = BlogArticleRouteImport.update({
  id: '/article',
  path: '/article',
  getParentRoute: () => BlogRoute,
} as any)
const ManagementMemberPreviewMemberIdRoute =
  ManagementMemberPreviewMemberIdRouteImport.update({
    id: '/management-member-preview/$memberId',
    path: '/management-member-preview/$memberId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMobileReturnRoute = PaymentMobileReturnRouteImport.update({
  id: '/payment/mobile-return',
  path: '/payment/mobile-return',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPublicCallbackRoute = PaymentPublicCallbackRouteImport.update({
  id: '/payment/public-callback',
  path: '/payment/public-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReceptionRoute = PortalReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStaffRoute = PortalStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => PortalRoute,
} as any)
const ReceptionMemberMemberIdRoute = ReceptionMemberMemberIdRouteImport.update({
  id: '/reception-member/$memberId',
  path: '/reception-member/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-announcements': typeof AdminAnnouncementsRoute
  '/admin-approvals': typeof AdminApprovalsRoute
  '/admin-engagement': typeof AdminEngagementRoute
  '/admin-historical-members': typeof AdminHistoricalMembersRoute
  '/admin-members': typeof AdminMembersRoute
  '/admin-workspace': typeof AdminWorkspaceRoute
  '/app': typeof AppRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/facilities': typeof FacilitiesRoute
  '/family-join': typeof FamilyJoinRoute
  '/gallery': typeof GalleryRoute
  '/hmo': typeof HmoRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/management-attendance': typeof ManagementAttendanceRoute
  '/management-attendance-export': typeof ManagementAttendanceExportRoute
  '/management-bookings': typeof ManagementBookingsRoute
  '/management-communications': typeof ManagementCommunicationsRoute
  '/management-custom-plan': typeof ManagementCustomPlanRoute
  '/management-expenses': typeof ManagementExpensesRoute
  '/management-family': typeof ManagementFamilyRoute
  '/management-member-card': typeof ManagementMemberCardRoute
  '/management-member-cards': typeof ManagementMemberCardsRoute
  '/management-member-feedback': typeof ManagementMemberFeedbackRoute
  '/management-members': typeof ManagementMembersRoute
  '/management-new-member-intake': typeof ManagementNewMemberIntakeRoute
  '/management-operations': typeof ManagementOperationsRoute
  '/management-payment-desk': typeof ManagementPaymentDeskRoute
  '/management-payroll': typeof ManagementPayrollRoute
  '/management-payroll-export': typeof ManagementPayrollExportRoute
  '/management-personal-training': typeof ManagementPersonalTrainingRoute
  '/management-preview': typeof ManagementPreviewRoute
  '/management-profiles': typeof ManagementProfilesRoute
  '/management-revenue': typeof ManagementRevenueRoute
  '/management-salary-payments': typeof ManagementSalaryPaymentsRoute
  '/management-staff': typeof ManagementStaffRoute
  '/management-staff-management': typeof ManagementStaffManagementRoute
  '/management-staff-monthly': typeof ManagementStaffMonthlyRoute
  '/management-staff-review': typeof ManagementStaffReviewRoute
  '/management-staff-support': typeof ManagementStaffSupportRoute
  '/management-standard-plan': typeof ManagementStandardPlanRoute
  '/member': typeof MemberRoute
  '/member-family': typeof MemberFamilyRoute
  '/membership': typeof MembershipRoute
  '/my-qr': typeof MyQrRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reception-checkin': typeof ReceptionCheckinRoute
  '/reception-dashboard': typeof ReceptionDashboardRoute
  '/reception-register': typeof ReceptionRegisterRoute
  '/reception-workspace': typeof ReceptionWorkspaceRoute
  '/spa-recovery': typeof SpaRecoveryRoute
  '/staff': typeof StaffRoute
  '/staff-account-requests': typeof StaffAccountRequestsRoute
  '/staff-admin': typeof StaffAdminRoute
  '/staff-attendance': typeof StaffAttendanceRoute
  '/staff-attendance-qr': typeof StaffAttendanceQrRoute
  '/staff-blog': typeof StaffBlogRoute
  '/staff-gallery': typeof StaffGalleryRoute
  '/staff-missed-scans': typeof StaffMissedScansRoute
  '/staff-reset-password': typeof StaffResetPasswordRoute
  '/terms': typeof TermsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/article': typeof BlogArticleRoute
  '/management-member-preview/$memberId': typeof ManagementMemberPreviewMemberIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/payment/mobile-return': typeof PaymentMobileReturnRoute
  '/payment/public-callback': typeof PaymentPublicCallbackRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/reception': typeof PortalReceptionRoute
  '/portal/staff': typeof PortalStaffRoute
  '/reception-member/$memberId': typeof ReceptionMemberMemberIdRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-announcements': typeof AdminAnnouncementsRoute
  '/admin-approvals': typeof AdminApprovalsRoute
  '/admin-engagement': typeof AdminEngagementRoute
  '/admin-historical-members': typeof AdminHistoricalMembersRoute
  '/admin-members': typeof AdminMembersRoute
  '/admin-workspace': typeof AdminWorkspaceRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/facilities': typeof FacilitiesRoute
  '/family-join': typeof FamilyJoinRoute
  '/gallery': typeof GalleryRoute
  '/hmo': typeof HmoRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/management-attendance': typeof ManagementAttendanceRoute
  '/management-attendance-export': typeof ManagementAttendanceExportRoute
  '/management-bookings': typeof ManagementBookingsRoute
  '/management-communications': typeof ManagementCommunicationsRoute
  '/management-custom-plan': typeof ManagementCustomPlanRoute
  '/management-expenses': typeof ManagementExpensesRoute
  '/management-family': typeof ManagementFamilyRoute
  '/management-member-card': typeof ManagementMemberCardRoute
  '/management-member-cards': typeof ManagementMemberCardsRoute
  '/management-member-feedback': typeof ManagementMemberFeedbackRoute
  '/management-members': typeof ManagementMembersRoute
  '/management-new-member-intake': typeof ManagementNewMemberIntakeRoute
  '/management-operations': typeof ManagementOperationsRoute
  '/management-payment-desk': typeof ManagementPaymentDeskRoute
  '/management-payroll': typeof ManagementPayrollRoute
  '/management-payroll-export': typeof ManagementPayrollExportRoute
  '/management-personal-training': typeof ManagementPersonalTrainingRoute
  '/management-preview': typeof ManagementPreviewRoute
  '/management-profiles': typeof ManagementProfilesRoute
  '/management-revenue': typeof ManagementRevenueRoute
  '/management-salary-payments': typeof ManagementSalaryPaymentsRoute
  '/management-staff': typeof ManagementStaffRoute
  '/management-staff-management': typeof ManagementStaffManagementRoute
  '/management-staff-monthly': typeof ManagementStaffMonthlyRoute
  '/management-staff-review': typeof ManagementStaffReviewRoute
  '/management-staff-support': typeof ManagementStaffSupportRoute
  '/management-standard-plan': typeof ManagementStandardPlanRoute
  '/member': typeof MemberRoute
  '/member-family': typeof MemberFamilyRoute
  '/membership': typeof MembershipRoute
  '/my-qr': typeof MyQrRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reception-checkin': typeof ReceptionCheckinRoute
  '/reception-dashboard': typeof ReceptionDashboardRoute
  '/reception-register': typeof ReceptionRegisterRoute
  '/reception-workspace': typeof ReceptionWorkspaceRoute
  '/spa-recovery': typeof SpaRecoveryRoute
  '/staff': typeof StaffRoute
  '/staff-account-requests': typeof StaffAccountRequestsRoute
  '/staff-admin': typeof StaffAdminRoute
  '/staff-attendance': typeof StaffAttendanceRoute
  '/staff-attendance-qr': typeof StaffAttendanceQrRoute
  '/staff-blog': typeof StaffBlogRoute
  '/staff-gallery': typeof StaffGalleryRoute
  '/staff-missed-scans': typeof StaffMissedScansRoute
  '/staff-reset-password': typeof StaffResetPasswordRoute
  '/terms': typeof TermsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/article': typeof BlogArticleRoute
  '/management-member-preview/$memberId': typeof ManagementMemberPreviewMemberIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/payment/mobile-return': typeof PaymentMobileReturnRoute
  '/payment/public-callback': typeof PaymentPublicCallbackRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/reception': typeof PortalReceptionRoute
  '/portal/staff': typeof PortalStaffRoute
  '/reception-member/$memberId': typeof ReceptionMemberMemberIdRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-announcements': typeof AdminAnnouncementsRoute
  '/admin-approvals': typeof AdminApprovalsRoute
  '/admin-engagement': typeof AdminEngagementRoute
  '/admin-historical-members': typeof AdminHistoricalMembersRoute
  '/admin-members': typeof AdminMembersRoute
  '/admin-workspace': typeof AdminWorkspaceRoute
  '/app': typeof AppRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/facilities': typeof FacilitiesRoute
  '/family-join': typeof FamilyJoinRoute
  '/gallery': typeof GalleryRoute
  '/hmo': typeof HmoRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/management-attendance': typeof ManagementAttendanceRoute
  '/management-attendance-export': typeof ManagementAttendanceExportRoute
  '/management-bookings': typeof ManagementBookingsRoute
  '/management-communications': typeof ManagementCommunicationsRoute
  '/management-custom-plan': typeof ManagementCustomPlanRoute
  '/management-expenses': typeof ManagementExpensesRoute
  '/management-family': typeof ManagementFamilyRoute
  '/management-member-card': typeof ManagementMemberCardRoute
  '/management-member-cards': typeof ManagementMemberCardsRoute
  '/management-member-feedback': typeof ManagementMemberFeedbackRoute
  '/management-members': typeof ManagementMembersRoute
  '/management-new-member-intake': typeof ManagementNewMemberIntakeRoute
  '/management-operations': typeof ManagementOperationsRoute
  '/management-payment-desk': typeof ManagementPaymentDeskRoute
  '/management-payroll': typeof ManagementPayrollRoute
  '/management-payroll-export': typeof ManagementPayrollExportRoute
  '/management-personal-training': typeof ManagementPersonalTrainingRoute
  '/management-preview': typeof ManagementPreviewRoute
  '/management-profiles': typeof ManagementProfilesRoute
  '/management-revenue': typeof ManagementRevenueRoute
  '/management-salary-payments': typeof ManagementSalaryPaymentsRoute
  '/management-staff': typeof ManagementStaffRoute
  '/management-staff-management': typeof ManagementStaffManagementRoute
  '/management-staff-monthly': typeof ManagementStaffMonthlyRoute
  '/management-staff-review': typeof ManagementStaffReviewRoute
  '/management-staff-support': typeof ManagementStaffSupportRoute
  '/management-standard-plan': typeof ManagementStandardPlanRoute
  '/member': typeof MemberRoute
  '/member-family': typeof MemberFamilyRoute
  '/membership': typeof MembershipRoute
  '/my-qr': typeof MyQrRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reception-checkin': typeof ReceptionCheckinRoute
  '/reception-dashboard': typeof ReceptionDashboardRoute
  '/reception-register': typeof ReceptionRegisterRoute
  '/reception-workspace': typeof ReceptionWorkspaceRoute
  '/spa-recovery': typeof SpaRecoveryRoute
  '/staff': typeof StaffRoute
  '/staff-account-requests': typeof StaffAccountRequestsRoute
  '/staff-admin': typeof StaffAdminRoute
  '/staff-attendance': typeof StaffAttendanceRoute
  '/staff-attendance-qr': typeof StaffAttendanceQrRoute
  '/staff-blog': typeof StaffBlogRoute
  '/staff-gallery': typeof StaffGalleryRoute
  '/staff-missed-scans': typeof StaffMissedScansRoute
  '/staff-reset-password': typeof StaffResetPasswordRoute
  '/terms': typeof TermsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/article': typeof BlogArticleRoute
  '/management-member-preview/$memberId': typeof ManagementMemberPreviewMemberIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/payment/mobile-return': typeof PaymentMobileReturnRoute
  '/payment/public-callback': typeof PaymentPublicCallbackRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/reception': typeof PortalReceptionRoute
  '/portal/staff': typeof PortalStaffRoute
  '/reception-member/$memberId': typeof ReceptionMemberMemberIdRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-announcements'
    | '/admin-approvals'
    | '/admin-engagement'
    | '/admin-historical-members'
    | '/admin-members'
    | '/admin-workspace'
    | '/app'
    | '/blog'
    | '/contact'
    | '/delete-account'
    | '/facilities'
    | '/family-join'
    | '/gallery'
    | '/hmo'
    | '/join'
    | '/login'
    | '/management-attendance'
    | '/management-attendance-export'
    | '/management-bookings'
    | '/management-communications'
    | '/management-custom-plan'
    | '/management-expenses'
    | '/management-family'
    | '/management-member-card'
    | '/management-member-cards'
    | '/management-member-feedback'
    | '/management-members'
    | '/management-new-member-intake'
    | '/management-operations'
    | '/management-payment-desk'
    | '/management-payroll'
    | '/management-payroll-export'
    | '/management-personal-training'
    | '/management-preview'
    | '/management-profiles'
    | '/management-revenue'
    | '/management-salary-payments'
    | '/management-staff'
    | '/management-staff-management'
    | '/management-staff-monthly'
    | '/management-staff-review'
    | '/management-staff-support'
    | '/management-standard-plan'
    | '/member'
    | '/member-family'
    | '/membership'
    | '/my-qr'
    | '/personal-training'
    | '/portal'
    | '/privacy-policy'
    | '/reception-checkin'
    | '/reception-dashboard'
    | '/reception-register'
    | '/reception-workspace'
    | '/spa-recovery'
    | '/staff'
    | '/staff-account-requests'
    | '/staff-admin'
    | '/staff-attendance'
    | '/staff-attendance-qr'
    | '/staff-blog'
    | '/staff-gallery'
    | '/staff-missed-scans'
    | '/staff-reset-password'
    | '/terms'
    | '/auth/confirm'
    | '/blog/$slug'
    | '/blog/article'
    | '/management-member-preview/$memberId'
    | '/payment/callback'
    | '/payment/mobile-return'
    | '/payment/public-callback'
    | '/portal/admin'
    | '/portal/reception'
    | '/portal/staff'
    | '/reception-member/$memberId'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-announcements'
    | '/admin-approvals'
    | '/admin-engagement'
    | '/admin-historical-members'
    | '/admin-members'
    | '/admin-workspace'
    | '/app'
    | '/contact'
    | '/delete-account'
    | '/facilities'
    | '/family-join'
    | '/gallery'
    | '/hmo'
    | '/join'
    | '/login'
    | '/management-attendance'
    | '/management-attendance-export'
    | '/management-bookings'
    | '/management-communications'
    | '/management-custom-plan'
    | '/management-expenses'
    | '/management-family'
    | '/management-member-card'
    | '/management-member-cards'
    | '/management-member-feedback'
    | '/management-members'
    | '/management-new-member-intake'
    | '/management-operations'
    | '/management-payment-desk'
    | '/management-payroll'
    | '/management-payroll-export'
    | '/management-personal-training'
    | '/management-preview'
    | '/management-profiles'
    | '/management-revenue'
    | '/management-salary-payments'
    | '/management-staff'
    | '/management-staff-management'
    | '/management-staff-monthly'
    | '/management-staff-review'
    | '/management-staff-support'
    | '/management-standard-plan'
    | '/member'
    | '/member-family'
    | '/membership'
    | '/my-qr'
    | '/personal-training'
    | '/portal'
    | '/privacy-policy'
    | '/reception-checkin'
    | '/reception-dashboard'
    | '/reception-register'
    | '/reception-workspace'
    | '/spa-recovery'
    | '/staff'
    | '/staff-account-requests'
    | '/staff-admin'
    | '/staff-attendance'
    | '/staff-attendance-qr'
    | '/staff-blog'
    | '/staff-gallery'
    | '/staff-missed-scans'
    | '/staff-reset-password'
    | '/terms'
    | '/auth/confirm'
    | '/blog/$slug'
    | '/blog/article'
    | '/management-member-preview/$memberId'
    | '/payment/callback'
    | '/payment/mobile-return'
    | '/payment/public-callback'
    | '/portal/admin'
    | '/portal/reception'
    | '/portal/staff'
    | '/reception-member/$memberId'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin-announcements'
    | '/admin-approvals'
    | '/admin-engagement'
    | '/admin-historical-members'
    | '/admin-members'
    | '/admin-workspace'
    | '/app'
    | '/blog'
    | '/contact'
    | '/delete-account'
    | '/facilities'
    | '/family-join'
    | '/gallery'
    | '/hmo'
    | '/join'
    | '/login'
    | '/management-attendance'
    | '/management-attendance-export'
    | '/management-bookings'
    | '/management-communications'
    | '/management-custom-plan'
    | '/management-expenses'
    | '/management-family'
    | '/management-member-card'
    | '/management-member-cards'
    | '/management-member-feedback'
    | '/management-members'
    | '/management-new-member-intake'
    | '/management-operations'
    | '/management-payment-desk'
    | '/management-payroll'
    | '/management-payroll-export'
    | '/management-personal-training'
    | '/management-preview'
    | '/management-profiles'
    | '/management-revenue'
    | '/management-salary-payments'
    | '/management-staff'
    | '/management-staff-management'
    | '/management-staff-monthly'
    | '/management-staff-review'
    | '/management-staff-support'
    | '/management-standard-plan'
    | '/member'
    | '/member-family'
    | '/membership'
    | '/my-qr'
    | '/personal-training'
    | '/portal'
    | '/privacy-policy'
    | '/reception-checkin'
    | '/reception-dashboard'
    | '/reception-register'
    | '/reception-workspace'
    | '/spa-recovery'
    | '/staff'
    | '/staff-account-requests'
    | '/staff-admin'
    | '/staff-attendance'
    | '/staff-attendance-qr'
    | '/staff-blog'
    | '/staff-gallery'
    | '/staff-missed-scans'
    | '/staff-reset-password'
    | '/terms'
    | '/auth/confirm'
    | '/blog/$slug'
    | '/blog/article'
    | '/management-member-preview/$memberId'
    | '/payment/callback'
    | '/payment/mobile-return'
    | '/payment/public-callback'
    | '/portal/admin'
    | '/portal/reception'
    | '/portal/staff'
    | '/reception-member/$memberId'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminEngagementRoute: typeof AdminEngagementRoute
  AdminHistoricalMembersRoute: typeof AdminHistoricalMembersRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminWorkspaceRoute: typeof AdminWorkspaceRoute
  AppRoute: typeof AppRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FamilyJoinRoute: typeof FamilyJoinRoute
  GalleryRoute: typeof GalleryRoute
  HmoRoute: typeof HmoRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  ManagementAttendanceRoute: typeof ManagementAttendanceRoute
  ManagementAttendanceExportRoute: typeof ManagementAttendanceExportRoute
  ManagementBookingsRoute: typeof ManagementBookingsRoute
  ManagementCommunicationsRoute: typeof ManagementCommunicationsRoute
  ManagementCustomPlanRoute: typeof ManagementCustomPlanRoute
  ManagementExpensesRoute: typeof ManagementExpensesRoute
  ManagementFamilyRoute: typeof ManagementFamilyRoute
  ManagementMemberCardRoute: typeof ManagementMemberCardRoute
  ManagementMemberCardsRoute: typeof ManagementMemberCardsRoute
  ManagementMemberFeedbackRoute: typeof ManagementMemberFeedbackRoute
  ManagementMembersRoute: typeof ManagementMembersRoute
  ManagementNewMemberIntakeRoute: typeof ManagementNewMemberIntakeRoute
  ManagementOperationsRoute: typeof ManagementOperationsRoute
  ManagementPaymentDeskRoute: typeof ManagementPaymentDeskRoute
  ManagementPayrollRoute: typeof ManagementPayrollRoute
  ManagementPayrollExportRoute: typeof ManagementPayrollExportRoute
  ManagementPersonalTrainingRoute: typeof ManagementPersonalTrainingRoute
  ManagementPreviewRoute: typeof ManagementPreviewRoute
  ManagementProfilesRoute: typeof ManagementProfilesRoute
  ManagementRevenueRoute: typeof ManagementRevenueRoute
  ManagementSalaryPaymentsRoute: typeof ManagementSalaryPaymentsRoute
  ManagementStaffRoute: typeof ManagementStaffRoute
  ManagementStaffManagementRoute: typeof ManagementStaffManagementRoute
  ManagementStaffMonthlyRoute: typeof ManagementStaffMonthlyRoute
  ManagementStaffReviewRoute: typeof ManagementStaffReviewRoute
  ManagementStaffSupportRoute: typeof ManagementStaffSupportRoute
  ManagementStandardPlanRoute: typeof ManagementStandardPlanRoute
  MemberRoute: typeof MemberRoute
  MemberFamilyRoute: typeof MemberFamilyRoute
  MembershipRoute: typeof MembershipRoute
  MyQrRoute: typeof MyQrRoute
  PersonalTrainingRoute: typeof PersonalTrainingRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReceptionCheckinRoute: typeof ReceptionCheckinRoute
  ReceptionDashboardRoute: typeof ReceptionDashboardRoute
  ReceptionRegisterRoute: typeof ReceptionRegisterRoute
  ReceptionWorkspaceRoute: typeof ReceptionWorkspaceRoute
  SpaRecoveryRoute: typeof SpaRecoveryRoute
  StaffRoute: typeof StaffRoute
  StaffAccountRequestsRoute: typeof StaffAccountRequestsRoute
  StaffAdminRoute: typeof StaffAdminRoute
  StaffAttendanceRoute: typeof StaffAttendanceRoute
  StaffAttendanceQrRoute: typeof StaffAttendanceQrRoute
  StaffBlogRoute: typeof StaffBlogRoute
  StaffGalleryRoute: typeof StaffGalleryRoute
  StaffMissedScansRoute: typeof StaffMissedScansRoute
  StaffResetPasswordRoute: typeof StaffResetPasswordRoute
  TermsRoute: typeof TermsRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  ManagementMemberPreviewMemberIdRoute: typeof ManagementMemberPreviewMemberIdRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  PaymentMobileReturnRoute: typeof PaymentMobileReturnRoute
  PaymentPublicCallbackRoute: typeof PaymentPublicCallbackRoute
  ReceptionMemberMemberIdRoute: typeof ReceptionMemberMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-announcements': {
      id: '/admin-announcements'
      path: '/admin-announcements'
      fullPath: '/admin-announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-approvals': {
      id: '/admin-approvals'
      path: '/admin-approvals'
      fullPath: '/admin-approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-engagement': {
      id: '/admin-engagement'
      path: '/admin-engagement'
      fullPath: '/admin-engagement'
      preLoaderRoute: typeof AdminEngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-historical-members': {
      id: '/admin-historical-members'
      path: '/admin-historical-members'
      fullPath: '/admin-historical-members'
      preLoaderRoute: typeof AdminHistoricalMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-members': {
      id: '/admin-members'
      path: '/admin-members'
      fullPath: '/admin-members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-workspace': {
      id: '/admin-workspace'
      path: '/admin-workspace'
      fullPath: '/admin-workspace'
      preLoaderRoute: typeof AdminWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-join': {
      id: '/family-join'
      path: '/family-join'
      fullPath: '/family-join'
      preLoaderRoute: typeof FamilyJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hmo': {
      id: '/hmo'
      path: '/hmo'
      fullPath: '/hmo'
      preLoaderRoute: typeof HmoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-attendance': {
      id: '/management-attendance'
      path: '/management-attendance'
      fullPath: '/management-attendance'
      preLoaderRoute: typeof ManagementAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-attendance-export': {
      id: '/management-attendance-export'
      path: '/management-attendance-export'
      fullPath: '/management-attendance-export'
      preLoaderRoute: typeof ManagementAttendanceExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-bookings': {
      id: '/management-bookings'
      path: '/management-bookings'
      fullPath: '/management-bookings'
      preLoaderRoute: typeof ManagementBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-communications': {
      id: '/management-communications'
      path: '/management-communications'
      fullPath: '/management-communications'
      preLoaderRoute: typeof ManagementCommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-custom-plan': {
      id: '/management-custom-plan'
      path: '/management-custom-plan'
      fullPath: '/management-custom-plan'
      preLoaderRoute: typeof ManagementCustomPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-expenses': {
      id: '/management-expenses'
      path: '/management-expenses'
      fullPath: '/management-expenses'
      preLoaderRoute: typeof ManagementExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-family': {
      id: '/management-family'
      path: '/management-family'
      fullPath: '/management-family'
      preLoaderRoute: typeof ManagementFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-member-card': {
      id: '/management-member-card'
      path: '/management-member-card'
      fullPath: '/management-member-card'
      preLoaderRoute: typeof ManagementMemberCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-member-cards': {
      id: '/management-member-cards'
      path: '/management-member-cards'
      fullPath: '/management-member-cards'
      preLoaderRoute: typeof ManagementMemberCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-member-feedback': {
      id: '/management-member-feedback'
      path: '/management-member-feedback'
      fullPath: '/management-member-feedback'
      preLoaderRoute: typeof ManagementMemberFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-members': {
      id: '/management-members'
      path: '/management-members'
      fullPath: '/management-members'
      preLoaderRoute: typeof ManagementMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-new-member-intake': {
      id: '/management-new-member-intake'
      path: '/management-new-member-intake'
      fullPath: '/management-new-member-intake'
      preLoaderRoute: typeof ManagementNewMemberIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-operations': {
      id: '/management-operations'
      path: '/management-operations'
      fullPath: '/management-operations'
      preLoaderRoute: typeof ManagementOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-payment-desk': {
      id: '/management-payment-desk'
      path: '/management-payment-desk'
      fullPath: '/management-payment-desk'
      preLoaderRoute: typeof ManagementPaymentDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-payroll': {
      id: '/management-payroll'
      path: '/management-payroll'
      fullPath: '/management-payroll'
      preLoaderRoute: typeof ManagementPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-payroll-export': {
      id: '/management-payroll-export'
      path: '/management-payroll-export'
      fullPath: '/management-payroll-export'
      preLoaderRoute: typeof ManagementPayrollExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-personal-training': {
      id: '/management-personal-training'
      path: '/management-personal-training'
      fullPath: '/management-personal-training'
      preLoaderRoute: typeof ManagementPersonalTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-preview': {
      id: '/management-preview'
      path: '/management-preview'
      fullPath: '/management-preview'
      preLoaderRoute: typeof ManagementPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-profiles': {
      id: '/management-profiles'
      path: '/management-profiles'
      fullPath: '/management-profiles'
      preLoaderRoute: typeof ManagementProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-revenue': {
      id: '/management-revenue'
      path: '/management-revenue'
      fullPath: '/management-revenue'
      preLoaderRoute: typeof ManagementRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-salary-payments': {
      id: '/management-salary-payments'
      path: '/management-salary-payments'
      fullPath: '/management-salary-payments'
      preLoaderRoute: typeof ManagementSalaryPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-staff': {
      id: '/management-staff'
      path: '/management-staff'
      fullPath: '/management-staff'
      preLoaderRoute: typeof ManagementStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-staff-management': {
      id: '/management-staff-management'
      path: '/management-staff-management'
      fullPath: '/management-staff-management'
      preLoaderRoute: typeof ManagementStaffManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-staff-monthly': {
      id: '/management-staff-monthly'
      path: '/management-staff-monthly'
      fullPath: '/management-staff-monthly'
      preLoaderRoute: typeof ManagementStaffMonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-staff-review': {
      id: '/management-staff-review'
      path: '/management-staff-review'
      fullPath: '/management-staff-review'
      preLoaderRoute: typeof ManagementStaffReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-staff-support': {
      id: '/management-staff-support'
      path: '/management-staff-support'
      fullPath: '/management-staff-support'
      preLoaderRoute: typeof ManagementStaffSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-standard-plan': {
      id: '/management-standard-plan'
      path: '/management-standard-plan'
      fullPath: '/management-standard-plan'
      preLoaderRoute: typeof ManagementStandardPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-family': {
      id: '/member-family'
      path: '/member-family'
      fullPath: '/member-family'
      preLoaderRoute: typeof MemberFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-qr': {
      id: '/my-qr'
      path: '/my-qr'
      fullPath: '/my-qr'
      preLoaderRoute: typeof MyQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-training': {
      id: '/personal-training'
      path: '/personal-training'
      fullPath: '/personal-training'
      preLoaderRoute: typeof PersonalTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception-checkin': {
      id: '/reception-checkin'
      path: '/reception-checkin'
      fullPath: '/reception-checkin'
      preLoaderRoute: typeof ReceptionCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception-dashboard': {
      id: '/reception-dashboard'
      path: '/reception-dashboard'
      fullPath: '/reception-dashboard'
      preLoaderRoute: typeof ReceptionDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception-register': {
      id: '/reception-register'
      path: '/reception-register'
      fullPath: '/reception-register'
      preLoaderRoute: typeof ReceptionRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception-workspace': {
      id: '/reception-workspace'
      path: '/reception-workspace'
      fullPath: '/reception-workspace'
      preLoaderRoute: typeof ReceptionWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spa-recovery': {
      id: '/spa-recovery'
      path: '/spa-recovery'
      fullPath: '/spa-recovery'
      preLoaderRoute: typeof SpaRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-account-requests': {
      id: '/staff-account-requests'
      path: '/staff-account-requests'
      fullPath: '/staff-account-requests'
      preLoaderRoute: typeof StaffAccountRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-admin': {
      id: '/staff-admin'
      path: '/staff-admin'
      fullPath: '/staff-admin'
      preLoaderRoute: typeof StaffAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-attendance': {
      id: '/staff-attendance'
      path: '/staff-attendance'
      fullPath: '/staff-attendance'
      preLoaderRoute: typeof StaffAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-attendance-qr': {
      id: '/staff-attendance-qr'
      path: '/staff-attendance-qr'
      fullPath: '/staff-attendance-qr'
      preLoaderRoute: typeof StaffAttendanceQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-blog': {
      id: '/staff-blog'
      path: '/staff-blog'
      fullPath: '/staff-blog'
      preLoaderRoute: typeof StaffBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-gallery': {
      id: '/staff-gallery'
      path: '/staff-gallery'
      fullPath: '/staff-gallery'
      preLoaderRoute: typeof StaffGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-missed-scans': {
      id: '/staff-missed-scans'
      path: '/staff-missed-scans'
      fullPath: '/staff-missed-scans'
      preLoaderRoute: typeof StaffMissedScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-reset-password': {
      id: '/staff-reset-password'
      path: '/staff-reset-password'
      fullPath: '/staff-reset-password'
      preLoaderRoute: typeof StaffResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/article': {
      id: '/blog/article'
      path: '/article'
      fullPath: '/blog/article'
      preLoaderRoute: typeof BlogArticleRouteImport
      parentRoute: typeof BlogRoute
    }
    '/management-member-preview/$memberId': {
      id: '/management-member-preview/$memberId'
      path: '/management-member-preview/$memberId'
      fullPath: '/management-member-preview/$memberId'
      preLoaderRoute: typeof ManagementMemberPreviewMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/mobile-return': {
      id: '/payment/mobile-return'
      path: '/payment/mobile-return'
      fullPath: '/payment/mobile-return'
      preLoaderRoute: typeof PaymentMobileReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/public-callback': {
      id: '/payment/public-callback'
      path: '/payment/public-callback'
      fullPath: '/payment/public-callback'
      preLoaderRoute: typeof PaymentPublicCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/admin': {
      id: '/portal/admin'
      path: '/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/reception': {
      id: '/portal/reception'
      path: '/reception'
      fullPath: '/portal/reception'
      preLoaderRoute: typeof PortalReceptionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/staff': {
      id: '/portal/staff'
      path: '/staff'
      fullPath: '/portal/staff'
      preLoaderRoute: typeof PortalStaffRouteImport
      parentRoute: typeof PortalRoute
    }
    '/reception-member/$memberId': {
      id: '/reception-member/$memberId'
      path: '/reception-member/$memberId'
      fullPath: '/reception-member/$memberId'
      preLoaderRoute: typeof ReceptionMemberMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogArticleRoute: typeof BlogArticleRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogArticleRoute: BlogArticleRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PortalRouteChildren {
  PortalAdminRoute: typeof PortalAdminRoute
  PortalReceptionRoute: typeof PortalReceptionRoute
  PortalStaffRoute: typeof PortalStaffRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAdminRoute: PortalAdminRoute,
  PortalReceptionRoute: PortalReceptionRoute,
  PortalStaffRoute: PortalStaffRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminEngagementRoute: AdminEngagementRoute,
  AdminHistoricalMembersRoute: AdminHistoricalMembersRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminWorkspaceRoute: AdminWorkspaceRoute,
  AppRoute: AppRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  FacilitiesRoute: FacilitiesRoute,
  FamilyJoinRoute: FamilyJoinRoute,
  GalleryRoute: GalleryRoute,
  HmoRoute: HmoRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  ManagementAttendanceRoute: ManagementAttendanceRoute,
  ManagementAttendanceExportRoute: ManagementAttendanceExportRoute,
  ManagementBookingsRoute: ManagementBookingsRoute,
  ManagementCommunicationsRoute: ManagementCommunicationsRoute,
  ManagementCustomPlanRoute: ManagementCustomPlanRoute,
  ManagementExpensesRoute: ManagementExpensesRoute,
  ManagementFamilyRoute: ManagementFamilyRoute,
  ManagementMemberCardRoute: ManagementMemberCardRoute,
  ManagementMemberCardsRoute: ManagementMemberCardsRoute,
  ManagementMemberFeedbackRoute: ManagementMemberFeedbackRoute,
  ManagementMembersRoute: ManagementMembersRoute,
  ManagementNewMemberIntakeRoute: ManagementNewMemberIntakeRoute,
  ManagementOperationsRoute: ManagementOperationsRoute,
  ManagementPaymentDeskRoute: ManagementPaymentDeskRoute,
  ManagementPayrollRoute: ManagementPayrollRoute,
  ManagementPayrollExportRoute: ManagementPayrollExportRoute,
  ManagementPersonalTrainingRoute: ManagementPersonalTrainingRoute,
  ManagementPreviewRoute: ManagementPreviewRoute,
  ManagementProfilesRoute: ManagementProfilesRoute,
  ManagementRevenueRoute: ManagementRevenueRoute,
  ManagementSalaryPaymentsRoute: ManagementSalaryPaymentsRoute,
  ManagementStaffRoute: ManagementStaffRoute,
  ManagementStaffManagementRoute: ManagementStaffManagementRoute,
  ManagementStaffMonthlyRoute: ManagementStaffMonthlyRoute,
  ManagementStaffReviewRoute: ManagementStaffReviewRoute,
  ManagementStaffSupportRoute: ManagementStaffSupportRoute,
  ManagementStandardPlanRoute: ManagementStandardPlanRoute,
  MemberRoute: MemberRoute,
  MemberFamilyRoute: MemberFamilyRoute,
  MembershipRoute: MembershipRoute,
  MyQrRoute: MyQrRoute,
  PersonalTrainingRoute: PersonalTrainingRoute,
  PortalRoute: PortalRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReceptionCheckinRoute: ReceptionCheckinRoute,
  ReceptionDashboardRoute: ReceptionDashboardRoute,
  ReceptionRegisterRoute: ReceptionRegisterRoute,
  ReceptionWorkspaceRoute: ReceptionWorkspaceRoute,
  SpaRecoveryRoute: SpaRecoveryRoute,
  StaffRoute: StaffRoute,
  StaffAccountRequestsRoute: StaffAccountRequestsRoute,
  StaffAdminRoute: StaffAdminRoute,
  StaffAttendanceRoute: StaffAttendanceRoute,
  StaffAttendanceQrRoute: StaffAttendanceQrRoute,
  StaffBlogRoute: StaffBlogRoute,
  StaffGalleryRoute: StaffGalleryRoute,
  StaffMissedScansRoute: StaffMissedScansRoute,
  StaffResetPasswordRoute: StaffResetPasswordRoute,
  TermsRoute: TermsRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  ManagementMemberPreviewMemberIdRoute: ManagementMemberPreviewMemberIdRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  PaymentMobileReturnRoute: PaymentMobileReturnRoute,
  PaymentPublicCallbackRoute: PaymentPublicCallbackRoute,
  ReceptionMemberMemberIdRoute: ReceptionMemberMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
