/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as HmoRouteImport } from './routes/hmo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemberRouteImport } from './routes/member'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MyQrRouteImport } from './routes/my-qr'
import { Route as PersonalTrainingRouteImport } from './routes/personal-training'
import { Route as ReceptionCheckinRouteImport } from './routes/reception-checkin'
import { Route as SpaRecoveryRouteImport } from './routes/spa-recovery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const HmoRoute = HmoRouteImport.update({
  id: '/hmo',
  path: '/hmo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQrRoute = MyQrRouteImport.update({
  id: '/my-qr',
  path: '/my-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalTrainingRoute = PersonalTrainingRouteImport.update({
  id: '/personal-training',
  path: '/personal-training',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionCheckinRoute = ReceptionCheckinRouteImport.update({
  id: '/reception-checkin',
  path: '/reception-checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaRecoveryRoute = SpaRecoveryRouteImport.update({
  id: '/spa-recovery',
  path: '/spa-recovery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/hmo': typeof HmoRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/membership': typeof MembershipRoute
  '/my-qr': typeof MyQrRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/reception-checkin': typeof ReceptionCheckinRoute
  '/spa-recovery': typeof SpaRecoveryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/hmo': typeof HmoRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/membership': typeof MembershipRoute
  '/my-qr': typeof MyQrRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/reception-checkin': typeof ReceptionCheckinRoute
  '/spa-recovery': typeof SpaRecoveryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/hmo': typeof HmoRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/membership': typeof MembershipRoute
  '/my-qr': typeof MyQrRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/reception-checkin': typeof ReceptionCheckinRoute
  '/spa-recovery': typeof SpaRecoveryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/facilities'
    | '/hmo'
    | '/login'
    | '/member'
    | '/membership'
    | '/my-qr'
    | '/personal-training'
    | '/reception-checkin'
    | '/spa-recovery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/facilities'
    | '/hmo'
    | '/login'
    | '/member'
    | '/membership'
    | '/my-qr'
    | '/personal-training'
    | '/reception-checkin'
    | '/spa-recovery'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/facilities'
    | '/hmo'
    | '/login'
    | '/member'
    | '/membership'
    | '/my-qr'
    | '/personal-training'
    | '/reception-checkin'
    | '/spa-recovery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FacilitiesRoute: typeof FacilitiesRoute
  HmoRoute: typeof HmoRoute
  LoginRoute: typeof LoginRoute
  MemberRoute: typeof MemberRoute
  MembershipRoute: typeof MembershipRoute
  MyQrRoute: typeof MyQrRoute
  PersonalTrainingRoute: typeof PersonalTrainingRoute
  ReceptionCheckinRoute: typeof ReceptionCheckinRoute
  SpaRecoveryRoute: typeof SpaRecoveryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hmo': {
      id: '/hmo'
      path: '/hmo'
      fullPath: '/hmo'
      preLoaderRoute: typeof HmoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-qr': {
      id: '/my-qr'
      path: '/my-qr'
      fullPath: '/my-qr'
      preLoaderRoute: typeof MyQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-training': {
      id: '/personal-training'
      path: '/personal-training'
      fullPath: '/personal-training'
      preLoaderRoute: typeof PersonalTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception-checkin': {
      id: '/reception-checkin'
      path: '/reception-checkin'
      fullPath: '/reception-checkin'
      preLoaderRoute: typeof ReceptionCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spa-recovery': {
      id: '/spa-recovery'
      path: '/spa-recovery'
      fullPath: '/spa-recovery'
      preLoaderRoute: typeof SpaRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FacilitiesRoute: FacilitiesRoute,
  HmoRoute: HmoRoute,
  LoginRoute: LoginRoute,
  MemberRoute: MemberRoute,
  MembershipRoute: MembershipRoute,
  MyQrRoute: MyQrRoute,
  PersonalTrainingRoute: PersonalTrainingRoute,
  ReceptionCheckinRoute: ReceptionCheckinRoute,
  SpaRecoveryRoute: SpaRecoveryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
