/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// It is kept in sync with the route files in src/routes.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogArticleRouteImport } from './routes/blog.article'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as HmoRouteImport } from './routes/hmo'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemberRouteImport } from './routes/member'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MyQrRouteImport } from './routes/my-qr'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as PaymentPublicCallbackRouteImport } from './routes/payment.public-callback'
import { Route as PersonalTrainingRouteImport } from './routes/personal-training'
import { Route as ReceptionCheckinRouteImport } from './routes/reception-checkin'
import { Route as ReceptionDashboardRouteImport } from './routes/reception-dashboard'
import { Route as ReceptionMemberMemberIdRouteImport } from './routes/reception-member.$memberId'
import { Route as SpaRecoveryRouteImport } from './routes/spa-recovery'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StaffAdminRouteImport } from './routes/staff-admin'
import { Route as StaffAttendanceQrRouteImport } from './routes/staff-attendance-qr'
import { Route as StaffAttendanceRouteImport } from './routes/staff-attendance'
import { Route as StaffBlogRouteImport } from './routes/staff-blog'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogArticleRoute = BlogArticleRouteImport.update({
  id: '/blog/article',
  path: '/blog/article',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const HmoRoute = HmoRouteImport.update({
  id: '/hmo',
  path: '/hmo',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQrRoute = MyQrRouteImport.update({
  id: '/my-qr',
  path: '/my-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPublicCallbackRoute = PaymentPublicCallbackRouteImport.update({
  id: '/payment/public-callback',
  path: '/payment/public-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalTrainingRoute = PersonalTrainingRouteImport.update({
  id: '/personal-training',
  path: '/personal-training',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionCheckinRoute = ReceptionCheckinRouteImport.update({
  id: '/reception-checkin',
  path: '/reception-checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionDashboardRoute = ReceptionDashboardRouteImport.update({
  id: '/reception-dashboard',
  path: '/reception-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionMemberMemberIdRoute = ReceptionMemberMemberIdRouteImport.update({
  id: '/reception-member/$memberId',
  path: '/reception-member/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaRecoveryRoute = SpaRecoveryRouteImport.update({
  id: '/spa-recovery',
  path: '/spa-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAdminRoute = StaffAdminRouteImport.update({
  id: '/staff-admin',
  path: '/staff-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAttendanceQrRoute = StaffAttendanceQrRouteImport.update({
  id: '/staff-attendance-qr',
  path: '/staff-attendance-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAttendanceRoute = StaffAttendanceRouteImport.update({
  id: '/staff-attendance',
  path: '/staff-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffBlogRoute = StaffBlogRouteImport.update({
  id: '/staff-blog',
  path: '/staff-blog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/blog': typeof BlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/article': typeof BlogArticleRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/hmo': typeof HmoRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/membership': typeof MembershipRoute
  '/my-qr': typeof MyQrRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/payment/public-callback': typeof PaymentPublicCallbackRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/reception-checkin': typeof ReceptionCheckinRoute
  '/reception-dashboard': typeof ReceptionDashboardRoute
  '/reception-member/$memberId': typeof ReceptionMemberMemberIdRoute
  '/spa-recovery': typeof SpaRecoveryRoute
  '/staff': typeof StaffRoute
  '/staff-admin': typeof StaffAdminRoute
  '/staff-attendance-qr': typeof StaffAttendanceQrRoute
  '/staff-attendance': typeof StaffAttendanceRoute
  '/staff-blog': typeof StaffBlogRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/blog': typeof BlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/article': typeof BlogArticleRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/hmo': typeof HmoRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/membership': typeof MembershipRoute
  '/my-qr': typeof MyQrRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/payment/public-callback': typeof PaymentPublicCallbackRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/reception-checkin': typeof ReceptionCheckinRoute
  '/reception-dashboard': typeof ReceptionDashboardRoute
  '/reception-member/$memberId': typeof ReceptionMemberMemberIdRoute
  '/spa-recovery': typeof SpaRecoveryRoute
  '/staff': typeof StaffRoute
  '/staff-admin': typeof StaffAdminRoute
  '/staff-attendance-qr': typeof StaffAttendanceQrRoute
  '/staff-attendance': typeof StaffAttendanceRoute
  '/staff-blog': typeof StaffBlogRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/blog': typeof BlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/article': typeof BlogArticleRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/hmo': typeof HmoRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/membership': typeof MembershipRoute
  '/my-qr': typeof MyQrRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/payment/public-callback': typeof PaymentPublicCallbackRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/reception-checkin': typeof ReceptionCheckinRoute
  '/reception-dashboard': typeof ReceptionDashboardRoute
  '/reception-member/$memberId': typeof ReceptionMemberMemberIdRoute
  '/spa-recovery': typeof SpaRecoveryRoute
  '/staff': typeof StaffRoute
  '/staff-admin': typeof StaffAdminRoute
  '/staff-attendance-qr': typeof StaffAttendanceQrRoute
  '/staff-attendance': typeof StaffAttendanceRoute
  '/staff-blog': typeof StaffBlogRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth/confirm'
    | '/blog'
    | '/blog/$slug'
    | '/blog/article'
    | '/contact'
    | '/facilities'
    | '/hmo'
    | '/join'
    | '/login'
    | '/member'
    | '/membership'
    | '/my-qr'
    | '/payment/callback'
    | '/payment/public-callback'
    | '/personal-training'
    | '/reception-checkin'
    | '/reception-dashboard'
    | '/reception-member/$memberId'
    | '/spa-recovery'
    | '/staff'
    | '/staff-admin'
    | '/staff-attendance-qr'
    | '/staff-attendance'
    | '/staff-blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth/confirm'
    | '/blog'
    | '/blog/$slug'
    | '/blog/article'
    | '/contact'
    | '/facilities'
    | '/hmo'
    | '/join'
    | '/login'
    | '/member'
    | '/membership'
    | '/my-qr'
    | '/payment/callback'
    | '/payment/public-callback'
    | '/personal-training'
    | '/reception-checkin'
    | '/reception-dashboard'
    | '/reception-member/$memberId'
    | '/spa-recovery'
    | '/staff'
    | '/staff-admin'
    | '/staff-attendance-qr'
    | '/staff-attendance'
    | '/staff-blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth/confirm'
    | '/blog'
    | '/blog/$slug'
    | '/blog/article'
    | '/contact'
    | '/facilities'
    | '/hmo'
    | '/join'
    | '/login'
    | '/member'
    | '/membership'
    | '/my-qr'
    | '/payment/callback'
    | '/payment/public-callback'
    | '/personal-training'
    | '/reception-checkin'
    | '/reception-dashboard'
    | '/reception-member/$memberId'
    | '/spa-recovery'
    | '/staff'
    | '/staff-admin'
    | '/staff-attendance-qr'
    | '/staff-attendance'
    | '/staff-blog'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  BlogRoute: typeof BlogRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogArticleRoute: typeof BlogArticleRoute
  ContactRoute: typeof ContactRoute
  FacilitiesRoute: typeof FacilitiesRoute
  HmoRoute: typeof HmoRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  MemberRoute: typeof MemberRoute
  MembershipRoute: typeof MembershipRoute
  MyQrRoute: typeof MyQrRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  PaymentPublicCallbackRoute: typeof PaymentPublicCallbackRoute
  PersonalTrainingRoute: typeof PersonalTrainingRoute
  ReceptionCheckinRoute: typeof ReceptionCheckinRoute
  ReceptionDashboardRoute: typeof ReceptionDashboardRoute
  ReceptionMemberMemberIdRoute: typeof ReceptionMemberMemberIdRoute
  SpaRecoveryRoute: typeof SpaRecoveryRoute
  StaffRoute: typeof StaffRoute
  StaffAdminRoute: typeof StaffAdminRoute
  StaffAttendanceQrRoute: typeof StaffAttendanceQrRoute
  StaffAttendanceRoute: typeof StaffAttendanceRoute
  StaffBlogRoute: typeof StaffBlogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/article': {
      id: '/blog/article'
      path: '/blog/article'
      fullPath: '/blog/article'
      preLoaderRoute: typeof BlogArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hmo': {
      id: '/hmo'
      path: '/hmo'
      fullPath: '/hmo'
      preLoaderRoute: typeof HmoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-qr': {
      id: '/my-qr'
      path: '/my-qr'
      fullPath: '/my-qr'
      preLoaderRoute: typeof MyQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/public-callback': {
      id: '/payment/public-callback'
      path: '/payment/public-callback'
      fullPath: '/payment/public-callback'
      preLoaderRoute: typeof PaymentPublicCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-training': {
      id: '/personal-training'
      path: '/personal-training'
      fullPath: '/personal-training'
      preLoaderRoute: typeof PersonalTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception-checkin': {
      id: '/reception-checkin'
      path: '/reception-checkin'
      fullPath: '/reception-checkin'
      preLoaderRoute: typeof ReceptionCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception-dashboard': {
      id: '/reception-dashboard'
      path: '/reception-dashboard'
      fullPath: '/reception-dashboard'
      preLoaderRoute: typeof ReceptionDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception-member/$memberId': {
      id: '/reception-member/$memberId'
      path: '/reception-member/$memberId'
      fullPath: '/reception-member/$memberId'
      preLoaderRoute: typeof ReceptionMemberMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spa-recovery': {
      id: '/spa-recovery'
      path: '/spa-recovery'
      fullPath: '/spa-recovery'
      preLoaderRoute: typeof SpaRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-admin': {
      id: '/staff-admin'
      path: '/staff-admin'
      fullPath: '/staff-admin'
      preLoaderRoute: typeof StaffAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-attendance-qr': {
      id: '/staff-attendance-qr'
      path: '/staff-attendance-qr'
      fullPath: '/staff-attendance-qr'
      preLoaderRoute: typeof StaffAttendanceQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-attendance': {
      id: '/staff-attendance'
      path: '/staff-attendance'
      fullPath: '/staff-attendance'
      preLoaderRoute: typeof StaffAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-blog': {
      id: '/staff-blog'
      path: '/staff-blog'
      fullPath: '/staff-blog'
      preLoaderRoute: typeof StaffBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  BlogRoute: BlogRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogArticleRoute: BlogArticleRoute,
  ContactRoute: ContactRoute,
  FacilitiesRoute: FacilitiesRoute,
  HmoRoute: HmoRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  MemberRoute: MemberRoute,
  MembershipRoute: MembershipRoute,
  MyQrRoute: MyQrRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  PaymentPublicCallbackRoute: PaymentPublicCallbackRoute,
  PersonalTrainingRoute: PersonalTrainingRoute,
  ReceptionCheckinRoute: ReceptionCheckinRoute,
  ReceptionDashboardRoute: ReceptionDashboardRoute,
  ReceptionMemberMemberIdRoute: ReceptionMemberMemberIdRoute,
  SpaRecoveryRoute: SpaRecoveryRoute,
  StaffRoute: StaffRoute,
  StaffAdminRoute: StaffAdminRoute,
  StaffAttendanceQrRoute: StaffAttendanceQrRoute,
  StaffAttendanceRoute: StaffAttendanceRoute,
  StaffBlogRoute: StaffBlogRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
